/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mwhScQxahW1in9QQ9WEhLw
// Component: 3UoNTlE6DfwL

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Navbar from "../../Navbar"; // plasmic-import: WRD9j93d1vlf/component
import Button from "../../Button"; // plasmic-import: zBHMtY0Q_-9b/component
import Personnaliser from "../../Personnaliser"; // plasmic-import: PzznN-H4TBjO/component
import YouTube from "@plasmicpkgs/react-youtube";
import Tester from "../../Tester"; // plasmic-import: 44WXQC_jtDCd/component
import BigFooter from "../../BigFooter"; // plasmic-import: fcdOVpZOWlXS/component

import { useScreenVariants as useScreenVariantsjC0Cb1S4E1Yt } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: jC0CB1S4E1YT/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: mwhScQxahW1in9QQ9WEhLw/projectcss
import sty from "./PlasmicWipCentralisation.module.css"; // plasmic-import: 3UoNTlE6DfwL/css

import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: IC7ycYphHpjw/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: 7sgNTXN-bhFB/icon
import _9025852PhoneCallIconSvgIcon from "./icons/PlasmicIcon___9025852PhoneCallIconSvg"; // plasmic-import: Yrry_94-feiz/icon

createPlasmicElementProxy;

export type PlasmicWipCentralisation__VariantMembers = {};
export type PlasmicWipCentralisation__VariantsArgs = {};
type VariantPropType = keyof PlasmicWipCentralisation__VariantsArgs;
export const PlasmicWipCentralisation__VariantProps =
  new Array<VariantPropType>();

export type PlasmicWipCentralisation__ArgsType = {};
type ArgPropType = keyof PlasmicWipCentralisation__ArgsType;
export const PlasmicWipCentralisation__ArgProps = new Array<ArgPropType>();

export type PlasmicWipCentralisation__OverridesType = {
  body?: Flex__<"div">;
  wrapper?: Flex__<"div">;
  presentation?: Flex__<"section">;
  navbar?: Flex__<typeof Navbar>;
  h1?: Flex__<"h1">;
  cta?: Flex__<"div">;
  cta2?: Flex__<"div">;
  personnalisation?: Flex__<"a"> & Partial<LinkProps>;
  conditionsPersonnalisation?: Flex__<"section">;
  numbers?: Flex__<"div">;
  accessibilite?: Flex__<"a"> & Partial<LinkProps>;
  conditionsAccessibilite?: Flex__<"section">;
  numbers2?: Flex__<"div">;
  automatisation?: Flex__<"a"> & Partial<LinkProps>;
  conditionsAccessibilite2?: Flex__<"section">;
  numbers3?: Flex__<"div">;
  apercu?: Flex__<"section">;
  youTube?: Flex__<typeof YouTube>;
  testez?: Flex__<"section">;
  bigFooter?: Flex__<typeof BigFooter>;
};

export interface DefaultWipCentralisationProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicWipCentralisation__RenderFunc(props: {
  variants: PlasmicWipCentralisation__VariantsArgs;
  args: PlasmicWipCentralisation__ArgsType;
  overrides: PlasmicWipCentralisation__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsjC0Cb1S4E1Yt()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"body"}
          data-plasmic-override={overrides.body}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.body
          )}
        >
          <div
            data-plasmic-name={"wrapper"}
            data-plasmic-override={overrides.wrapper}
            className={classNames(projectcss.all, sty.wrapper)}
          >
            <section
              data-plasmic-name={"presentation"}
              data-plasmic-override={overrides.presentation}
              className={classNames(projectcss.all, sty.presentation)}
            >
              <Navbar
                data-plasmic-name={"navbar"}
                data-plasmic-override={overrides.navbar}
                className={classNames("__wab_instance", sty.navbar)}
              />

              <h1
                data-plasmic-name={"h1"}
                data-plasmic-override={overrides.h1}
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1
                )}
              >
                {"Natalia, l\u2019assistante vocale et email des pros"}
              </h1>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__r1Epr
                )}
              >
                {
                  "D\u00e9veloppez vos ventes directes en facilitant l'acc\u00e8s \u00e0 votre offre"
                }
              </div>
              <div
                data-plasmic-name={"cta"}
                data-plasmic-override={overrides.cta}
                className={classNames(projectcss.all, sty.cta)}
              >
                <Button
                  className={classNames("__wab_instance", sty.button__toGp)}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___1TMmk
                      )}
                    >
                      {"Personnalisation"}
                    </div>
                  }
                  linkTo={"#personnalisation"}
                  openLinkInNewTab={false}
                />

                <Button
                  ariaLabel={``}
                  className={classNames("__wab_instance", sty.button__rpSo4)}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__q6Gcc
                      )}
                    >
                      {"Accessiblit\u00e9"}
                    </div>
                  }
                  linkTo={"#accessibilite"}
                  openLinkInNewTab={false}
                />
              </div>
              <div
                data-plasmic-name={"cta2"}
                data-plasmic-override={overrides.cta2}
                className={classNames(projectcss.all, sty.cta2)}
              >
                <Button
                  ariaLabel={``}
                  className={classNames("__wab_instance", sty.button__bxRuh)}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gsBB
                      )}
                    >
                      {"Automatisation"}
                    </div>
                  }
                  linkTo={"#automatisation"}
                  openLinkInNewTab={false}
                />
              </div>
            </section>
            <PlasmicLink__
              data-plasmic-name={"personnalisation"}
              data-plasmic-override={overrides.personnalisation}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.personnalisation
              )}
              component={Link}
              id={"personnalisation"}
              platform={"nextjs"}
            >
              <div className={classNames(projectcss.all, sty.freeBox__xRaFc)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___94CwH)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__bktqi)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__w5UNe)}
                      displayHeight={"365px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/natalia_v_2/images/promptAFuturisticBusinessEnvironmentW1Svg.svg",
                        fullWidth: 1365,
                        fullHeight: 1024,
                        aspectRatio: 1.333008
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__brHc7)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__m59Vi
                      )}
                    >
                      {"Personnalisation"}
                    </div>
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__x4BDe
                      )}
                    >
                      {"Adaptez vos offres \u00e0 chaque client"}
                    </h2>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xlMsy
                      )}
                    >
                      {
                        "Pour maximiser vos ventes, il est essentiel de structurer vos propositions : chaque client est unique et cela doit \u00eatre per\u00e7u \u00e0 travers vos services. \n\nGr\u00e2ce \u00e0 Natalia, la gestion et la mise \u00e0 jour de ces offres sp\u00e9cifiques devient un jeu d\u2019enfant."
                      }
                    </div>
                  </div>
                </div>
                <section
                  data-plasmic-name={"conditionsPersonnalisation"}
                  data-plasmic-override={overrides.conditionsPersonnalisation}
                  className={classNames(
                    projectcss.all,
                    sty.conditionsPersonnalisation
                  )}
                >
                  <div
                    data-plasmic-name={"numbers"}
                    data-plasmic-override={overrides.numbers}
                    className={classNames(projectcss.all, sty.numbers)}
                  >
                    <Personnaliser
                      className={classNames(
                        "__wab_instance",
                        sty.personnaliser___0RXj
                      )}
                    />

                    <Personnaliser
                      className={classNames(
                        "__wab_instance",
                        sty.personnaliser__tCjnm
                      )}
                      description={
                        "G\u00e9rez vos tarifs par famille de clients ou par client.Chaque client ne verra que les tarifs qui le concerne."
                      }
                      img={{
                        src: "/plasmic/natalia_v_2/images/image10.png",
                        fullWidth: 86,
                        fullHeight: 86,
                        aspectRatio: undefined
                      }}
                      titre={"Tarifs sp\u00e9cifiques"}
                    />

                    <Personnaliser
                      className={classNames(
                        "__wab_instance",
                        sty.personnaliser___77Qtv
                      )}
                      description={
                        "G\u00e9rez vos francos, minimum de commande et jours de livraison disponibles par secteur ou par client."
                      }
                      img={{
                        src: "/plasmic/natalia_v_2/images/image11.png",
                        fullWidth: 86,
                        fullHeight: 86,
                        aspectRatio: undefined
                      }}
                      titre={"Conditions de vente"}
                    />
                  </div>
                </section>
              </div>
            </PlasmicLink__>
            <PlasmicLink__
              data-plasmic-name={"accessibilite"}
              data-plasmic-override={overrides.accessibilite}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.accessibilite
              )}
              component={Link}
              id={"accessibilite"}
              platform={"nextjs"}
            >
              <div className={classNames(projectcss.all, sty.freeBox__rgMhY)}>
                <div className={classNames(projectcss.all, sty.freeBox__rSxW)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__y3Z8T)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3JSnr
                      )}
                    >
                      {"Accessibilit\u00e9"}
                    </div>
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__sFBmt
                      )}
                    >
                      {"Chouchoutez et fid\u00e9lisez vos clients"}
                    </h2>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__cgwW
                      )}
                    >
                      {
                        "Vous souhaitez booster vos ventes ? \n\nOffrez \u00e0 vos clients un moyen simple, s\u00e9curis\u00e9 et efficace pour passer leurs commandes, tout en renfor\u00e7ant leur fid\u00e9lit\u00e9."
                      }
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__qEkL)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__mtOLp
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__eboJp)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/natalia_v_2/images/image16.png",
                            fullWidth: 86,
                            fullHeight: 86,
                            aspectRatio: undefined
                          }}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wus2S
                          )}
                        >
                          {"100% direct \n0 commission"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___2KdWt
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__rPcEg)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/natalia_v_2/images/image17.png",
                            fullWidth: 86,
                            fullHeight: 86,
                            aspectRatio: undefined
                          }}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___0DqD
                          )}
                        >
                          {"Chat int\u00e9gr\u00e9"}
                        </div>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ewwoA)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__ms6Kb)}
                      displayHeight={"365px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/natalia_v_2/images/promptAModernAndWelcomingBusinessEnvSvg.svg",
                        fullWidth: 1365,
                        fullHeight: 1024,
                        aspectRatio: 1.333008
                      }}
                    />
                  </div>
                </div>
                <section
                  data-plasmic-name={"conditionsAccessibilite"}
                  data-plasmic-override={overrides.conditionsAccessibilite}
                  className={classNames(
                    projectcss.all,
                    sty.conditionsAccessibilite
                  )}
                >
                  <div
                    data-plasmic-name={"numbers2"}
                    data-plasmic-override={overrides.numbers2}
                    className={classNames(projectcss.all, sty.numbers2)}
                  >
                    <Personnaliser
                      className={classNames(
                        "__wab_instance",
                        sty.personnaliser__noSPp
                      )}
                      description={
                        "G\u00e9n\u00e9rez en 1 clic une mini boutique en ligne, partagez le lien en priv\u00e9 ou diffusez-le sur tous vos r\u00e9seaux !"
                      }
                      img={{
                        src: "/plasmic/natalia_v_2/images/image12.png",
                        fullWidth: 86,
                        fullHeight: 86,
                        aspectRatio: undefined
                      }}
                      titre={"Page vitrine de vos produits"}
                    />

                    <Personnaliser
                      className={classNames(
                        "__wab_instance",
                        sty.personnaliser__i7UH
                      )}
                      description={
                        "Offrez \u00e0 vos clients un suivi fiable et en temps r\u00e9el du traitement de leurs commandes"
                      }
                      img={{
                        src: "/plasmic/natalia_v_2/images/image14.png",
                        fullWidth: 86,
                        fullHeight: 86,
                        aspectRatio: undefined
                      }}
                      titre={"Suivi en temps r\u00e9el"}
                    />

                    <Personnaliser
                      className={classNames(
                        "__wab_instance",
                        sty.personnaliser__aCzs
                      )}
                      description={
                        "Donnez-leur acc\u00e8s \u00e0 leur historique de commandes et documents (bons de commande, de livraison et factures)"
                      }
                      img={{
                        src: "/plasmic/natalia_v_2/images/image15.png",
                        fullWidth: 86,
                        fullHeight: 86,
                        aspectRatio: undefined
                      }}
                      titre={"Historique et docs"}
                    />
                  </div>
                </section>
              </div>
            </PlasmicLink__>
            <PlasmicLink__
              data-plasmic-name={"automatisation"}
              data-plasmic-override={overrides.automatisation}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.automatisation
              )}
              component={Link}
              id={"automatisation"}
              platform={"nextjs"}
            >
              <div className={classNames(projectcss.all, sty.freeBox__hkvbr)}>
                <div className={classNames(projectcss.all, sty.freeBox___4PGd)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__i5HkQ)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__nInCh)}
                      displayHeight={"365px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/natalia_v_2/images/promptAFuturisticOfficeEnvironmentWhe1Svg.svg",
                        fullWidth: 1365,
                        fullHeight: 1024,
                        aspectRatio: 1.333008
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__lgmwe)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__s4Vn8
                      )}
                    >
                      {"Automatisation"}
                    </div>
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__fq2N
                      )}
                    >
                      {
                        "Optimisez vos processus avec l'intelligence artificielle"
                      }
                    </h2>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rgzIl
                      )}
                    >
                      {
                        "Ne perdez plus de temps avec la gestion manuelle des appels et emails. \n\nGr\u00e2ce \u00e0 Natalia, l'automatisation de ces t\u00e2ches r\u00e9duit de 30 % votre charge administrative et am\u00e9liore votre r\u00e9activit\u00e9."
                      }
                    </div>
                  </div>
                </div>
                <section
                  data-plasmic-name={"conditionsAccessibilite2"}
                  data-plasmic-override={overrides.conditionsAccessibilite2}
                  className={classNames(
                    projectcss.all,
                    sty.conditionsAccessibilite2
                  )}
                >
                  <div
                    data-plasmic-name={"numbers3"}
                    data-plasmic-override={overrides.numbers3}
                    className={classNames(projectcss.all, sty.numbers3)}
                  >
                    <Personnaliser
                      className={classNames(
                        "__wab_instance",
                        sty.personnaliser__hQoMh
                      )}
                      description={
                        "Lisy g\u00e9n\u00e8re automatiquement les bons de commande et livraison \u00e0 partir des commandes."
                      }
                      img={{
                        src: "/plasmic/natalia_v_2/images/image18.png",
                        fullWidth: 86,
                        fullHeight: 86,
                        aspectRatio: undefined
                      }}
                      titre={"Gestion des documents"}
                    />

                    <Personnaliser
                      className={classNames(
                        "__wab_instance",
                        sty.personnaliser___2ZtCp
                      )}
                      description={
                        "G\u00e9rez facilement la tra\u00e7abilit\u00e9 (num\u00e9ros de lots, DLC) des produits, et gardez un oeil sur vos dispo produits et stocks qui s'actualisent en temps r\u00e9el !"
                      }
                      img={{
                        src: "/plasmic/natalia_v_2/images/image19.png",
                        fullWidth: 86,
                        fullHeight: 86,
                        aspectRatio: undefined
                      }}
                      titre={
                        "Suivi des stocks et tra\u00e7abilit\u00e9 produits"
                      }
                    />

                    <Personnaliser
                      className={classNames(
                        "__wab_instance",
                        sty.personnaliser__si3Sk
                      )}
                      description={
                        "Lisy g\u00e9n\u00e8re automatiquement les factures par commande ou en fin de mois.G\u00e9n\u00e9rez les relances et exportez les donn\u00e9es au comptable en 1 clic."
                      }
                      img={{
                        src: "/plasmic/natalia_v_2/images/image11.png",
                        fullWidth: 86,
                        fullHeight: 86,
                        aspectRatio: undefined
                      }}
                      titre={"G\u00e9n\u00e9ration auto des factures"}
                    />
                  </div>
                </section>
              </div>
            </PlasmicLink__>
            <section
              data-plasmic-name={"apercu"}
              data-plasmic-override={overrides.apercu}
              className={classNames(projectcss.all, sty.apercu)}
            >
              <div className={classNames(projectcss.all, sty.freeBox___2Mht)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__emYsi
                  )}
                >
                  {"Aper\u00e7u de l'interface"}
                </h2>
                <YouTube
                  data-plasmic-name={"youTube"}
                  data-plasmic-override={overrides.youTube}
                  className={classNames("__wab_instance", sty.youTube)}
                  videoId={"R6MeLqRQzYw"}
                />
              </div>
            </section>
            <section
              data-plasmic-name={"testez"}
              data-plasmic-override={overrides.testez}
              className={classNames(projectcss.all, sty.testez)}
            >
              <div className={classNames(projectcss.all, sty.freeBox___25Coq)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__bu5S2
                  )}
                >
                  {"Testez en un rien de temps"}
                </h2>
                <div className={classNames(projectcss.all, sty.freeBox__ylw15)}>
                  <Tester
                    className={classNames("__wab_instance", sty.tester__ahKak)}
                    description={
                      "Vous avez besoin du mail sur lequel vous voulez les notifs en cas de nouvelle commande - les coordonn\u00e9es \u00e0 afficher pour vos clients (nous ne sommes pas un interm\u00e9diaire)"
                    }
                  />

                  <Tester
                    _2={["_2"]}
                    className={classNames("__wab_instance", sty.tester__irzDx)}
                    description={
                      "Automatiquement depuis une interface (ex: Shopify), en important un fichier Excel ou en cr\u00e9ant votre catalogue directement sur Lisy.On est l\u00e0 pour vous aider \ud83d\ude09"
                    }
                    img={{
                      src: "/plasmic/natalia_v_2/images/_8665197CircleArrowDownIconSvg.svg",
                      fullWidth: 512,
                      fullHeight: 512,
                      aspectRatio: 1
                    }}
                    titre={"2. Importez vos produits"}
                  />

                  <Tester
                    _3={["_3"]}
                    className={classNames("__wab_instance", sty.tester__gu5WV)}
                    description={
                      "Invitez vos clients en priv\u00e9, partagez votre catalogue sur vos r\u00e9seaux, connectez votre site ou saisissez vous-m\u00eame des commandes : les bons, les factures, le suivi du stock... tout devient automatique \ud83e\udd29"
                    }
                    titre={"3. Traitez vos commandes"}
                  />
                </div>
              </div>
            </section>
            <BigFooter
              data-plasmic-name={"bigFooter"}
              data-plasmic-override={overrides.bigFooter}
              className={classNames("__wab_instance", sty.bigFooter)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  body: [
    "body",
    "wrapper",
    "presentation",
    "navbar",
    "h1",
    "cta",
    "cta2",
    "personnalisation",
    "conditionsPersonnalisation",
    "numbers",
    "accessibilite",
    "conditionsAccessibilite",
    "numbers2",
    "automatisation",
    "conditionsAccessibilite2",
    "numbers3",
    "apercu",
    "youTube",
    "testez",
    "bigFooter"
  ],
  wrapper: [
    "wrapper",
    "presentation",
    "navbar",
    "h1",
    "cta",
    "cta2",
    "personnalisation",
    "conditionsPersonnalisation",
    "numbers",
    "accessibilite",
    "conditionsAccessibilite",
    "numbers2",
    "automatisation",
    "conditionsAccessibilite2",
    "numbers3",
    "apercu",
    "youTube",
    "testez",
    "bigFooter"
  ],
  presentation: ["presentation", "navbar", "h1", "cta", "cta2"],
  navbar: ["navbar"],
  h1: ["h1"],
  cta: ["cta"],
  cta2: ["cta2"],
  personnalisation: [
    "personnalisation",
    "conditionsPersonnalisation",
    "numbers"
  ],
  conditionsPersonnalisation: ["conditionsPersonnalisation", "numbers"],
  numbers: ["numbers"],
  accessibilite: ["accessibilite", "conditionsAccessibilite", "numbers2"],
  conditionsAccessibilite: ["conditionsAccessibilite", "numbers2"],
  numbers2: ["numbers2"],
  automatisation: ["automatisation", "conditionsAccessibilite2", "numbers3"],
  conditionsAccessibilite2: ["conditionsAccessibilite2", "numbers3"],
  numbers3: ["numbers3"],
  apercu: ["apercu", "youTube"],
  youTube: ["youTube"],
  testez: ["testez"],
  bigFooter: ["bigFooter"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  body: "div";
  wrapper: "div";
  presentation: "section";
  navbar: typeof Navbar;
  h1: "h1";
  cta: "div";
  cta2: "div";
  personnalisation: "a";
  conditionsPersonnalisation: "section";
  numbers: "div";
  accessibilite: "a";
  conditionsAccessibilite: "section";
  numbers2: "div";
  automatisation: "a";
  conditionsAccessibilite2: "section";
  numbers3: "div";
  apercu: "section";
  youTube: typeof YouTube;
  testez: "section";
  bigFooter: typeof BigFooter;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicWipCentralisation__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicWipCentralisation__VariantsArgs;
    args?: PlasmicWipCentralisation__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicWipCentralisation__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicWipCentralisation__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicWipCentralisation__ArgProps,
          internalVariantPropNames: PlasmicWipCentralisation__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicWipCentralisation__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "body") {
    func.displayName = "PlasmicWipCentralisation";
  } else {
    func.displayName = `PlasmicWipCentralisation.${nodeName}`;
  }
  return func;
}

export const PlasmicWipCentralisation = Object.assign(
  // Top-level PlasmicWipCentralisation renders the root element
  makeNodeComponent("body"),
  {
    // Helper components rendering sub-elements
    wrapper: makeNodeComponent("wrapper"),
    presentation: makeNodeComponent("presentation"),
    navbar: makeNodeComponent("navbar"),
    h1: makeNodeComponent("h1"),
    cta: makeNodeComponent("cta"),
    cta2: makeNodeComponent("cta2"),
    personnalisation: makeNodeComponent("personnalisation"),
    conditionsPersonnalisation: makeNodeComponent("conditionsPersonnalisation"),
    numbers: makeNodeComponent("numbers"),
    accessibilite: makeNodeComponent("accessibilite"),
    conditionsAccessibilite: makeNodeComponent("conditionsAccessibilite"),
    numbers2: makeNodeComponent("numbers2"),
    automatisation: makeNodeComponent("automatisation"),
    conditionsAccessibilite2: makeNodeComponent("conditionsAccessibilite2"),
    numbers3: makeNodeComponent("numbers3"),
    apercu: makeNodeComponent("apercu"),
    youTube: makeNodeComponent("youTube"),
    testez: makeNodeComponent("testez"),
    bigFooter: makeNodeComponent("bigFooter"),

    // Metadata about props expected for PlasmicWipCentralisation
    internalVariantProps: PlasmicWipCentralisation__VariantProps,
    internalArgProps: PlasmicWipCentralisation__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicWipCentralisation;
/* prettier-ignore-end */
