// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mwhScQxahW1in9QQ9WEhLw
// Component: GpFdzmhF4-uh

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Navbar from "../../Navbar"; // plasmic-import: WRD9j93d1vlf/component
import Chiffres from "../../Chiffres"; // plasmic-import: 8BGjQZUgzyum/component
import { SliderWrapper } from "@plasmicpkgs/react-slick";
import { sliderHelpers as SliderWrapper_Helpers } from "@plasmicpkgs/react-slick";
import Partenaire from "../../Partenaire"; // plasmic-import: HwyJBTEgZPTV/component
import Button from "../../Button"; // plasmic-import: zBHMtY0Q_-9b/component
import Footer from "../../Footer"; // plasmic-import: eVSkuc1xKJir/component

import { useScreenVariants as useScreenVariantsjC0Cb1S4E1Yt } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: jC0CB1S4E1YT/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: mwhScQxahW1in9QQ9WEhLw/projectcss
import sty from "./PlasmicPartenaires.module.css"; // plasmic-import: GpFdzmhF4-uh/css

import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: IC7ycYphHpjw/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: 7sgNTXN-bhFB/icon

createPlasmicElementProxy;

export type PlasmicPartenaires__VariantMembers = {};
export type PlasmicPartenaires__VariantsArgs = {};
type VariantPropType = keyof PlasmicPartenaires__VariantsArgs;
export const PlasmicPartenaires__VariantProps = new Array<VariantPropType>();

export type PlasmicPartenaires__ArgsType = {};
type ArgPropType = keyof PlasmicPartenaires__ArgsType;
export const PlasmicPartenaires__ArgProps = new Array<ArgPropType>();

export type PlasmicPartenaires__OverridesType = {
  body?: Flex__<"div">;
  wrapper?: Flex__<"div">;
  presentation?: Flex__<"section">;
  navbar?: Flex__<typeof Navbar>;
  chiffres?: Flex__<"section">;
  chiffres2?: Flex__<"div">;
  sliderCarousel?: Flex__<typeof SliderWrapper>;
  partenaires?: Flex__<"section">;
  titre?: Flex__<"div">;
  retour?: Flex__<"section">;
  button?: Flex__<typeof Button>;
  footer?: Flex__<"section">;
  callUs?: Flex__<typeof Button>;
};

export interface DefaultPartenairesProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPartenaires__RenderFunc(props: {
  variants: PlasmicPartenaires__VariantsArgs;
  args: PlasmicPartenaires__ArgsType;
  overrides: PlasmicPartenaires__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "sliderCarousel.currentSlide",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0,

        refName: "sliderCarousel",
        onMutate: generateOnMutateForSpec("currentSlide", SliderWrapper_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsjC0Cb1S4E1Yt()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicPartenaires.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicPartenaires.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicPartenaires.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicPartenaires.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicPartenaires.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicPartenaires.pageMetadata.description}
        />

        <link
          rel="canonical"
          href={PlasmicPartenaires.pageMetadata.canonical}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"body"}
          data-plasmic-override={overrides.body}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.body
          )}
        >
          <div
            data-plasmic-name={"wrapper"}
            data-plasmic-override={overrides.wrapper}
            className={classNames(projectcss.all, sty.wrapper)}
          >
            <section
              data-plasmic-name={"presentation"}
              data-plasmic-override={overrides.presentation}
              className={classNames(projectcss.all, sty.presentation)}
            >
              <Navbar
                data-plasmic-name={"navbar"}
                data-plasmic-override={overrides.navbar}
                className={classNames("__wab_instance", sty.navbar)}
              />

              <h1
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1__f3YgP
                )}
              >
                {"Ensemble on avance plus vite !"}
              </h1>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__haGz
                )}
              >
                {
                  "Un immense merci \u00e0 nos partenaires qui ont contribu\u00e9 \u00e0 faire de cette aventure une r\u00e9ussite ! \ud83d\ude80"
                }
              </div>
            </section>
            <section
              data-plasmic-name={"chiffres"}
              data-plasmic-override={overrides.chiffres}
              className={classNames(projectcss.all, sty.chiffres)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"chiffres2"}
                data-plasmic-override={overrides.chiffres2}
                hasGap={true}
                className={classNames(projectcss.all, sty.chiffres2)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__p62EG)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__q2NlJ)}
                  >
                    <Chiffres
                      className={classNames(
                        "__wab_instance",
                        sty.chiffres__mrZz4
                      )}
                      description={``}
                      nb={"2"}
                      sousTitre={"partenaires"}
                    />

                    <Chiffres
                      className={classNames(
                        "__wab_instance",
                        sty.chiffres__bKlc
                      )}
                      description={``}
                      nb={"4"}
                      sousTitre={"int\u00e9grations"}
                    />

                    <Chiffres
                      className={classNames(
                        "__wab_instance",
                        sty.chiffres__apP
                      )}
                      description={``}
                      nb={"x%"}
                      sousTitre={"d'efficacit\u00e9"}
                    />

                    <Chiffres
                      className={classNames(
                        "__wab_instance",
                        sty.chiffres__ucZiD
                      )}
                      description={``}
                      nb={"x"}
                      sousTitre={"projets d\u00e9ploy\u00e9s"}
                    />
                  </Stack__>
                  {(() => {
                    const child$Props = {
                      autoplay: true,
                      beforeChange: async (...eventArgs: any) => {
                        generateStateOnChangePropForCodeComponents(
                          $state,
                          "currentSlide",
                          ["sliderCarousel", "currentSlide"],
                          SliderWrapper_Helpers
                        ).apply(null, eventArgs);
                      },
                      className: classNames(
                        "__wab_instance",
                        sty.sliderCarousel
                      ),
                      initialSlide: generateStateValueProp($state, [
                        "sliderCarousel",
                        "currentSlide"
                      ]),
                      ref: ref => {
                        $refs["sliderCarousel"] = ref;
                      },
                      sliderScopeClassName: sty["sliderCarousel__slider"]
                    };
                    initializeCodeComponentStates(
                      $state,
                      [
                        {
                          name: "currentSlide",
                          plasmicStateName: "sliderCarousel.currentSlide"
                        }
                      ],
                      [],
                      SliderWrapper_Helpers ?? {},
                      child$Props
                    );

                    return (
                      <SliderWrapper
                        data-plasmic-name={"sliderCarousel"}
                        data-plasmic-override={overrides.sliderCarousel}
                        {...child$Props}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__gu73
                          )}
                        >
                          <Chiffres
                            className={classNames(
                              "__wab_instance",
                              sty.chiffres___0HeJh
                            )}
                            description={``}
                            nb={"2"}
                            sousTitre={"partenaires"}
                          />
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__po1Jj
                          )}
                        >
                          <Chiffres
                            className={classNames(
                              "__wab_instance",
                              sty.chiffres__gcNKo
                            )}
                            description={``}
                            nb={"4"}
                            sousTitre={"int\u00e9grations"}
                          />
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__vIdIz
                          )}
                        >
                          <Chiffres
                            className={classNames(
                              "__wab_instance",
                              sty.chiffres__zGito
                            )}
                            description={``}
                            nb={"x%"}
                            sousTitre={"d'efficacit\u00e9"}
                          />
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__aobb6
                          )}
                        >
                          <Chiffres
                            className={classNames(
                              "__wab_instance",
                              sty.chiffres___5BFb5
                            )}
                            description={``}
                            nb={"x"}
                            sousTitre={"projets d\u00e9ploy\u00e9s"}
                          />
                        </div>
                      </SliderWrapper>
                    );
                  })()}
                </Stack__>
              </Stack__>
            </section>
            <section
              data-plasmic-name={"partenaires"}
              data-plasmic-override={overrides.partenaires}
              className={classNames(projectcss.all, sty.partenaires)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___6PxWo)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"titre"}
                  data-plasmic-override={overrides.titre}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.titre)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__mY6Xb)}
                  >
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2___54Klr
                      )}
                    >
                      {"Nos partenaires"}
                    </h2>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fdf3H
                      )}
                    >
                      {
                        "Sans eux, Natalia ne serait pas l\u00e0 aujourd\u2019hui. Un grand merci \u00e0 nos partenaires pour leur soutien pr\u00e9cieux ! "
                      }
                    </div>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__y2NRt)}
                >
                  <Partenaire
                    className={classNames(
                      "__wab_instance",
                      sty.partenaire__fyph4
                    )}
                    description={
                      "La CCI Vend\u00e9e et Natalia s\u2019associent pour accompagner les entreprises locales dans leur transformation digitale. Gr\u00e2ce \u00e0 ce partenariat, les entrepreneurs vend\u00e9ens b\u00e9n\u00e9ficient d\u2019un acc\u00e8s privil\u00e9gi\u00e9 \u00e0 des solutions num\u00e9riques adapt\u00e9es \u00e0 leurs besoins, simplifiant ainsi leur gestion et leur d\u00e9veloppement. Ensemble, nous facilitons l\u2019innovation et l\u2019efficacit\u00e9 des acteurs \u00e9conomiques du territoire."
                    }
                  />

                  <Partenaire
                    className={classNames(
                      "__wab_instance",
                      sty.partenaire__fnvAt
                    )}
                    description={
                      "Natalia rejoint l\u2019\u00e9cosyst\u00e8me dynamique de la French Tech et de la French Tech Vend\u00e9e pour soutenir les startups et entreprises innovantes. Ce partenariat favorise l\u2019\u00e9mergence de solutions technologiques performantes et renforce la comp\u00e9titivit\u00e9 des entrepreneurs fran\u00e7ais. En collaborant avec la French Tech, Natalia participe activement \u00e0 la croissance et \u00e0 la r\u00e9ussite des projets num\u00e9riques de demain."
                    }
                    img={{
                      src: "/plasmic/natalia_v_2/images/image26.png",
                      fullWidth: 375,
                      fullHeight: 474,
                      aspectRatio: undefined
                    }}
                    nom={"La French Tech"}
                  />
                </Stack__>
              </Stack__>
            </section>
            <section
              data-plasmic-name={"retour"}
              data-plasmic-override={overrides.retour}
              className={classNames(projectcss.all, sty.retour)}
            >
              <Button
                data-plasmic-name={"button"}
                data-plasmic-override={overrides.button}
                className={classNames("__wab_instance", sty.button)}
                label={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mZiNf
                    )}
                  >
                    {"Retour \u00e0 l'accueil"}
                  </div>
                }
                linkTo={`/`}
              />
            </section>
            <section
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames(projectcss.all, sty.footer)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___3F0F3
                )}
              >
                {"DECOUVRIR"}
              </div>
              <h1
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1__le8Dd
                )}
              >
                <React.Fragment>
                  <React.Fragment>{""}</React.Fragment>
                  {
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__nxUtB
                      )}
                    >
                      {"Pr\u00eat \u00e0 transformer votre relation client ?"}
                    </h2>
                  }
                  <React.Fragment>{""}</React.Fragment>
                </React.Fragment>
              </h1>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ybrL
                )}
              >
                {
                  "Offrez une exp\u00e9rience m\u00e9morable \u00e0 vos clients, gagnez en productivit\u00e9 et laissez Natalia s\u2019occuper du reste."
                }
              </div>
              <Button
                data-plasmic-name={"callUs"}
                data-plasmic-override={overrides.callUs}
                className={classNames("__wab_instance", sty.callUs)}
                label={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pO9LE
                    )}
                  >
                    {"Prendre rendez-vous"}
                  </div>
                }
                linkTo={
                  "mailto:getnatalia@getnatalia.com?subject=Demande%20d'acc\u00e8s%20\u00e0%20Natalia&body=Bonjour%20%2C%0A%0AJe%20souhaite%20obtenir%20un%20acc\u00e8s%20\u00e0%20votre%20solution%20Natalia.%20Voici%20mes%20informations%20:%0A%0ANom%20:%20%0AEntreprise%20:%20%0AEmail%20:%20%0A%0AMerci%20de%20me%20revenir%20rapidement.%0A%0ACordialement,%0A[Votre%20Nom]"
                }
                openLinkInNewTab={true}
              />

              <Footer
                className={classNames("__wab_instance", sty.footer__iu99D)}
              />
            </section>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  body: [
    "body",
    "wrapper",
    "presentation",
    "navbar",
    "chiffres",
    "chiffres2",
    "sliderCarousel",
    "partenaires",
    "titre",
    "retour",
    "button",
    "footer",
    "callUs"
  ],
  wrapper: [
    "wrapper",
    "presentation",
    "navbar",
    "chiffres",
    "chiffres2",
    "sliderCarousel",
    "partenaires",
    "titre",
    "retour",
    "button",
    "footer",
    "callUs"
  ],
  presentation: ["presentation", "navbar"],
  navbar: ["navbar"],
  chiffres: ["chiffres", "chiffres2", "sliderCarousel"],
  chiffres2: ["chiffres2", "sliderCarousel"],
  sliderCarousel: ["sliderCarousel"],
  partenaires: ["partenaires", "titre"],
  titre: ["titre"],
  retour: ["retour", "button"],
  button: ["button"],
  footer: ["footer", "callUs"],
  callUs: ["callUs"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  body: "div";
  wrapper: "div";
  presentation: "section";
  navbar: typeof Navbar;
  chiffres: "section";
  chiffres2: "div";
  sliderCarousel: typeof SliderWrapper;
  partenaires: "section";
  titre: "div";
  retour: "section";
  button: typeof Button;
  footer: "section";
  callUs: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPartenaires__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPartenaires__VariantsArgs;
    args?: PlasmicPartenaires__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPartenaires__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicPartenaires__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPartenaires__ArgProps,
          internalVariantPropNames: PlasmicPartenaires__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPartenaires__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "body") {
    func.displayName = "PlasmicPartenaires";
  } else {
    func.displayName = `PlasmicPartenaires.${nodeName}`;
  }
  return func;
}

export const PlasmicPartenaires = Object.assign(
  // Top-level PlasmicPartenaires renders the root element
  makeNodeComponent("body"),
  {
    // Helper components rendering sub-elements
    wrapper: makeNodeComponent("wrapper"),
    presentation: makeNodeComponent("presentation"),
    navbar: makeNodeComponent("navbar"),
    chiffres: makeNodeComponent("chiffres"),
    chiffres2: makeNodeComponent("chiffres2"),
    sliderCarousel: makeNodeComponent("sliderCarousel"),
    partenaires: makeNodeComponent("partenaires"),
    titre: makeNodeComponent("titre"),
    retour: makeNodeComponent("retour"),
    button: makeNodeComponent("button"),
    footer: makeNodeComponent("footer"),
    callUs: makeNodeComponent("callUs"),

    // Metadata about props expected for PlasmicPartenaires
    internalVariantProps: PlasmicPartenaires__VariantProps,
    internalArgProps: PlasmicPartenaires__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Partenaires de Natalia : Acteurs engagés du numérique",
      description:
        "Découvrez nos partenaires, CCI Vendée et French Tech, qui soutiennent Natalia dans l’accompagnement des entreprises vers des solutions numériques adaptées.",
      ogImageSrc: "",
      canonical: "https://getnatalia.com/partenaires"
    }
  }
);

export default PlasmicPartenaires;
/* prettier-ignore-end */
