/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mwhScQxahW1in9QQ9WEhLw
// Component: HwyJBTEgZPTV

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { useScreenVariants as useScreenVariantsjC0Cb1S4E1Yt } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: jC0CB1S4E1YT/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: mwhScQxahW1in9QQ9WEhLw/projectcss
import sty from "./PlasmicPartenaire.module.css"; // plasmic-import: HwyJBTEgZPTV/css

createPlasmicElementProxy;

export type PlasmicPartenaire__VariantMembers = {};
export type PlasmicPartenaire__VariantsArgs = {};
type VariantPropType = keyof PlasmicPartenaire__VariantsArgs;
export const PlasmicPartenaire__VariantProps = new Array<VariantPropType>();

export type PlasmicPartenaire__ArgsType = {
  img?: React.ComponentProps<typeof PlasmicImg__>["src"];
  nom?: string;
  description?: string;
};
type ArgPropType = keyof PlasmicPartenaire__ArgsType;
export const PlasmicPartenaire__ArgProps = new Array<ArgPropType>(
  "img",
  "nom",
  "description"
);

export type PlasmicPartenaire__OverridesType = {
  partenaire?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  h2?: Flex__<"h2">;
  text?: Flex__<"div">;
};

export interface DefaultPartenaireProps {
  img?: React.ComponentProps<typeof PlasmicImg__>["src"];
  nom?: string;
  description?: string;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPartenaire__RenderFunc(props: {
  variants: PlasmicPartenaire__VariantsArgs;
  args: PlasmicPartenaire__ArgsType;
  overrides: PlasmicPartenaire__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          img: {
            src: "/plasmic/natalia_v_2/images/image25.svg",
            fullWidth: 96.07,
            fullHeight: 29.68,
            aspectRatio: 3.23686
          },
          nom: "CCI",
          description:
            "Tr\u00e8s investi dans l'accompagnement des producteurs et des transitions agricoles, le CA Atlantique Vend\u00e9e a choisi Lisy comme partenaire pour aider ses clients qui le souhaitent \u00e0 se lancer en circuit court. Lisy leur offre la possibilit\u00e9 de tester tr\u00e8s simplement, et trouver de nouveaux d\u00e9bouch\u00e9s en diversifiant leurs canaux de vente. De plus, les clients du CA Atlantique Vend\u00e9e font b\u00e9n\u00e9ficier \u00e0 leurs clients de 20% de r\u00e9duction sur les offres Lisy gr\u00e2ce \u00e0 notre partenariat !"
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsjC0Cb1S4E1Yt()
  });

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"partenaire"}
      data-plasmic-override={overrides.partenaire}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.partenaire
      )}
    >
      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__qpz8H)}
      >
        <PlasmicImg__
          data-plasmic-name={"img"}
          data-plasmic-override={overrides.img}
          alt={""}
          className={classNames(sty.img)}
          displayHeight={"auto"}
          displayMaxHeight={"200px"}
          displayMaxWidth={"auto"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"auto"}
          loading={"lazy"}
          src={args.img}
        />
      </Stack__>
      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__isAiE)}
      >
        <Stack__
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__diRvn)}
        >
          <h2
            data-plasmic-name={"h2"}
            data-plasmic-override={overrides.h2}
            className={classNames(
              projectcss.all,
              projectcss.h2,
              projectcss.__wab_text,
              sty.h2
            )}
          >
            <React.Fragment>
              {(() => {
                try {
                  return $props.nom;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "CCI Vend\u00e9e";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          </h2>
          <div
            data-plasmic-name={"text"}
            data-plasmic-override={overrides.text}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text
            )}
          >
            <React.Fragment>
              {(() => {
                try {
                  return $props.description;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "Tr\u00e8s investi dans l'accompagnement des producteurs et des transitions agricoles, le CA Atlantique Vend\u00e9e a choisi Lisy comme partenaire pour aider ses clients qui le souhaitent \u00e0 se lancer en circuit court.\nLisy leur offre la possibilit\u00e9 de tester tr\u00e8s simplement, et trouver de nouveaux d\u00e9bouch\u00e9s en diversifiant leurs canaux de vente. De plus, les clients du CA Atlantique Vend\u00e9e font b\u00e9n\u00e9ficier \u00e0 leurs clients de 20% de r\u00e9duction sur les offres Lisy gr\u00e2ce \u00e0 notre partenariat !";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          </div>
        </Stack__>
      </Stack__>
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  partenaire: ["partenaire", "img", "h2", "text"],
  img: ["img"],
  h2: ["h2"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  partenaire: "div";
  img: typeof PlasmicImg__;
  h2: "h2";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPartenaire__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPartenaire__VariantsArgs;
    args?: PlasmicPartenaire__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPartenaire__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPartenaire__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPartenaire__ArgProps,
          internalVariantPropNames: PlasmicPartenaire__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPartenaire__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "partenaire") {
    func.displayName = "PlasmicPartenaire";
  } else {
    func.displayName = `PlasmicPartenaire.${nodeName}`;
  }
  return func;
}

export const PlasmicPartenaire = Object.assign(
  // Top-level PlasmicPartenaire renders the root element
  makeNodeComponent("partenaire"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    h2: makeNodeComponent("h2"),
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicPartenaire
    internalVariantProps: PlasmicPartenaire__VariantProps,
    internalArgProps: PlasmicPartenaire__ArgProps
  }
);

export default PlasmicPartenaire;
/* prettier-ignore-end */
