// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mwhScQxahW1in9QQ9WEhLw
// Component: RRkfys9gsrtt

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Navbar from "../../Navbar"; // plasmic-import: WRD9j93d1vlf/component
import Button from "../../Button"; // plasmic-import: zBHMtY0Q_-9b/component
import Personnaliser from "../../Personnaliser"; // plasmic-import: PzznN-H4TBjO/component
import YouTube from "@plasmicpkgs/react-youtube";
import Tester from "../../Tester"; // plasmic-import: 44WXQC_jtDCd/component
import Partenaire from "../../Partenaire"; // plasmic-import: HwyJBTEgZPTV/component
import BigFooter from "../../BigFooter"; // plasmic-import: fcdOVpZOWlXS/component

import { useScreenVariants as useScreenVariantsjC0Cb1S4E1Yt } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: jC0CB1S4E1YT/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: mwhScQxahW1in9QQ9WEhLw/projectcss
import sty from "./PlasmicAssistanteVocale.module.css"; // plasmic-import: RRkfys9gsrtt/css

import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: IC7ycYphHpjw/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: 7sgNTXN-bhFB/icon
import _8666632PhoneIconSvgIcon from "./icons/PlasmicIcon___8666632PhoneIconSvg"; // plasmic-import: YjVqrW6aV-Xz/icon
import _8666771FilterFunnelIconSvgIcon from "./icons/PlasmicIcon___8666771FilterFunnelIconSvg"; // plasmic-import: 9M_bXaSriyHG/icon
import _9042371ChatBubbleCheck1MessageIconSvgIcon from "./icons/PlasmicIcon___9042371ChatBubbleCheck1MessageIconSvg"; // plasmic-import: HreH8oqEjGWZ/icon
import _9989690SearchEngineInternetTechnologyResearchIconSvgIcon from "./icons/PlasmicIcon___9989690SearchEngineInternetTechnologyResearchIconSvg"; // plasmic-import: C87fX7RllPrB/icon
import _7787577SettingGearSettingsOptionsPreferencesIconSvgIcon from "./icons/PlasmicIcon___7787577SettingGearSettingsOptionsPreferencesIconSvg"; // plasmic-import: bO0Zrp0LpHXg/icon
import _8665779LinkConnectionIconSvgIcon from "./icons/PlasmicIcon___8665779LinkConnectionIconSvg"; // plasmic-import: _Xo752c7AVWn/icon

createPlasmicElementProxy;

export type PlasmicAssistanteVocale__VariantMembers = {};
export type PlasmicAssistanteVocale__VariantsArgs = {};
type VariantPropType = keyof PlasmicAssistanteVocale__VariantsArgs;
export const PlasmicAssistanteVocale__VariantProps =
  new Array<VariantPropType>();

export type PlasmicAssistanteVocale__ArgsType = {};
type ArgPropType = keyof PlasmicAssistanteVocale__ArgsType;
export const PlasmicAssistanteVocale__ArgProps = new Array<ArgPropType>();

export type PlasmicAssistanteVocale__OverridesType = {
  body?: Flex__<"div">;
  wrapper?: Flex__<"div">;
  presentation?: Flex__<"section">;
  navbar?: Flex__<typeof Navbar>;
  h1?: Flex__<"h1">;
  cta?: Flex__<"div">;
  cta2?: Flex__<"div">;
  accessibilite?: Flex__<"a"> & Partial<LinkProps>;
  conditionsAccessibilite?: Flex__<"section">;
  numbers2?: Flex__<"div">;
  apercu?: Flex__<"section">;
  youTube?: Flex__<typeof YouTube>;
  tester?: Flex__<typeof Tester>;
  automatisation?: Flex__<"a"> & Partial<LinkProps>;
  reponsesHomogenes?: Flex__<"div">;
  conditionsAccessibilite2?: Flex__<"section">;
  numbers3?: Flex__<"div">;
  personnalisation?: Flex__<"a"> & Partial<LinkProps>;
  conditionsPersonnalisation?: Flex__<"section">;
  numbers?: Flex__<"div">;
  partenaire?: Flex__<typeof Partenaire>;
  bigFooter?: Flex__<typeof BigFooter>;
};

export interface DefaultAssistanteVocaleProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAssistanteVocale__RenderFunc(props: {
  variants: PlasmicAssistanteVocale__VariantsArgs;
  args: PlasmicAssistanteVocale__ArgsType;
  overrides: PlasmicAssistanteVocale__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsjC0Cb1S4E1Yt()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{PlasmicAssistanteVocale.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicAssistanteVocale.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicAssistanteVocale.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicAssistanteVocale.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicAssistanteVocale.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicAssistanteVocale.pageMetadata.description}
        />
        <meta
          key="og:image"
          property="og:image"
          content={PlasmicAssistanteVocale.pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          name="twitter:image"
          content={PlasmicAssistanteVocale.pageMetadata.ogImageSrc}
        />
        <link
          rel="canonical"
          href={PlasmicAssistanteVocale.pageMetadata.canonical}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"body"}
          data-plasmic-override={overrides.body}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.body
          )}
        >
          <div
            data-plasmic-name={"wrapper"}
            data-plasmic-override={overrides.wrapper}
            className={classNames(projectcss.all, sty.wrapper)}
          >
            <section
              data-plasmic-name={"presentation"}
              data-plasmic-override={overrides.presentation}
              className={classNames(projectcss.all, sty.presentation)}
            >
              <Navbar
                data-plasmic-name={"navbar"}
                data-plasmic-override={overrides.navbar}
                className={classNames("__wab_instance", sty.navbar)}
              />

              <h1
                data-plasmic-name={"h1"}
                data-plasmic-override={overrides.h1}
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1
                )}
              >
                {"Natalia, l\u2019assistante vocale disponible 24/7"}
              </h1>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zIp5Z
                )}
              >
                {
                  "D\u00e9veloppez vos ventes directes en facilitant l'acc\u00e8s \u00e0 votre offre"
                }
              </div>
              <Stack__
                as={"div"}
                data-plasmic-name={"cta"}
                data-plasmic-override={overrides.cta}
                hasGap={true}
                className={classNames(projectcss.all, sty.cta)}
              >
                <Button
                  ariaLabel={``}
                  className={classNames("__wab_instance", sty.button__nbtmu)}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__oOxgP
                      )}
                    >
                      {"Accessiblit\u00e9"}
                    </div>
                  }
                  linkTo={"#accessibilite"}
                  openLinkInNewTab={false}
                />

                <Button
                  ariaLabel={``}
                  className={classNames("__wab_instance", sty.button__b9Upf)}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bXKe
                      )}
                    >
                      {"Uniformit\u00e9"}
                    </div>
                  }
                  linkTo={"#automatisation"}
                  openLinkInNewTab={false}
                />
              </Stack__>
              <div
                data-plasmic-name={"cta2"}
                data-plasmic-override={overrides.cta2}
                className={classNames(projectcss.all, sty.cta2)}
              >
                <Button
                  className={classNames("__wab_instance", sty.button__fP91D)}
                  disabled={false}
                  flatSide={[]}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yjpX
                      )}
                    >
                      {"Personnalisation"}
                    </div>
                  }
                  linkTo={"#personnalisation"}
                  openLinkInNewTab={false}
                />
              </div>
            </section>
            <PlasmicLink__
              data-plasmic-name={"accessibilite"}
              data-plasmic-override={overrides.accessibilite}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.accessibilite
              )}
              component={Link}
              id={"accessibilite"}
              platform={"nextjs"}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__sWqG6)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__o8YHu)}>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__nTz6B)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__iUfqm
                      )}
                    >
                      {"Accessibilit\u00e9"}
                    </div>
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__p8Rqa
                      )}
                    >
                      {"Disponible 24/7"}
                    </h2>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3Jg1B
                      )}
                    >
                      {
                        "Ne passez plus \u00e0 c\u00f4t\u00e9 des opportunit\u00e9s, soyez disponibles 24/7 pour vos clients et prospects. \n\nLa r\u00e9activit\u00e9 est cl\u00e9 pour offrir une exp\u00e9rience optimale \u00e0 vos clients.\n\nNatalia saura g\u00e9rer vos pics d'appels en r\u00e9pondant simultan\u00e9ment aux clients, vos clients n'attendront plus 5 minutes au bout du fil."
                      }
                    </div>
                  </Stack__>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___5EFg)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___7QOs5)}
                      displayHeight={"365px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/natalia_v_2/images/promptAModernAndWelcomingBusinessEnvSvg.svg",
                        fullWidth: 1365,
                        fullHeight: 1024,
                        aspectRatio: 1.333008
                      }}
                    />
                  </div>
                </div>
                <section
                  data-plasmic-name={"conditionsAccessibilite"}
                  data-plasmic-override={overrides.conditionsAccessibilite}
                  className={classNames(
                    projectcss.all,
                    sty.conditionsAccessibilite
                  )}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"numbers2"}
                    data-plasmic-override={overrides.numbers2}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.numbers2)}
                  >
                    <Personnaliser
                      className={classNames(
                        "__wab_instance",
                        sty.personnaliser___9Iilu
                      )}
                      description={
                        "Natalia peut r\u00e9pondre \u00e0 30 appels en simultan\u00e9, cela vous permet de d\u00e9sengorger vos centres d'appels et \u00eatre s\u00fbr de ne pas passer \u00e0 c\u00f4t\u00e9 d'opportunit\u00e9s."
                      }
                      img={{
                        src: "/plasmic/natalia_v_2/images/image12.png",
                        fullWidth: 86,
                        fullHeight: 86,
                        aspectRatio: undefined
                      }}
                      titre={"R\u00e9pondez \u00e0 tous les appels"}
                    >
                      <_8666632PhoneIconSvgIcon
                        className={classNames(projectcss.all, sty.svg__xx9QW)}
                        role={"img"}
                      />
                    </Personnaliser>
                    <Personnaliser
                      className={classNames(
                        "__wab_instance",
                        sty.personnaliser__v6VhK
                      )}
                      description={
                        "Natalia pose les bonnes questions, r\u00e9pond aux interrogations, planifie des rendez-vous. Cela vous assure la tra\u00e7abilit\u00e9 de l'information et vous fait gagner du temps, beaucoup de temps !"
                      }
                      img={{
                        src: "/plasmic/natalia_v_2/images/image15.png",
                        fullWidth: 86,
                        fullHeight: 86,
                        aspectRatio: undefined
                      }}
                      titre={"Pr\u00e9-qualifier vos leads"}
                    >
                      <_8666771FilterFunnelIconSvgIcon
                        className={classNames(projectcss.all, sty.svg___3J1Dr)}
                        role={"img"}
                      />
                    </Personnaliser>
                  </Stack__>
                </section>
              </Stack__>
            </PlasmicLink__>
            <section
              data-plasmic-name={"apercu"}
              data-plasmic-override={overrides.apercu}
              className={classNames(projectcss.all, sty.apercu)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__d42Lo)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__iO3K
                  )}
                >
                  {"Exemple appel Natalia"}
                </h2>
                <YouTube
                  data-plasmic-name={"youTube"}
                  data-plasmic-override={overrides.youTube}
                  className={classNames("__wab_instance", sty.youTube)}
                  videoId={"R6MeLqRQzYw"}
                />
              </Stack__>
            </section>
            <Tester
              data-plasmic-name={"tester"}
              data-plasmic-override={overrides.tester}
              className={classNames("__wab_instance", sty.tester)}
              description={
                "Ne perdez plus de temps pour des appels inutiles, Natalia prend le relai, restez focus."
              }
              img={{
                src: "/plasmic/natalia_v_2/images/captureDecran20250206A101324Png.png",
                fullWidth: 492,
                fullHeight: 490,
                aspectRatio: undefined
              }}
              titre={"Transfert des appels"}
            />

            <PlasmicLink__
              data-plasmic-name={"automatisation"}
              data-plasmic-override={overrides.automatisation}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.automatisation
              )}
              component={Link}
              id={"automatisation"}
              platform={"nextjs"}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___0BJpZ)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__tvhc0)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ryMz0)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__e8V0)}
                      displayHeight={"365px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/natalia_v_2/images/promptAFuturisticOfficeEnvironmentWhe1Svg.svg",
                        fullWidth: 1365,
                        fullHeight: 1024,
                        aspectRatio: 1.333008
                      }}
                    />
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__k8BC1)}
                  >
                    <div
                      data-plasmic-name={"reponsesHomogenes"}
                      data-plasmic-override={overrides.reponsesHomogenes}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.reponsesHomogenes
                      )}
                    >
                      {"Uniformit\u00e9"}
                    </div>
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__pm9Vg
                      )}
                    >
                      {"Une qualit\u00e9 de r\u00e9ponse homog\u00e8ne"}
                    </h2>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jHAoH
                      )}
                    >
                      {
                        "La satisfaction client c'est aussi avoir le bon interlocuteur qui connait ses produits, qui est exp\u00e9riment\u00e9, patient et toujours agr\u00e9able au t\u00e9l\u00e9phone.\n\nDifficile de v\u00e9hiculer le discours commercial et les valeurs de l'entreprises et \u00eatre certain de l'ex\u00e9cution, avec Natalia c'est d\u00e9sormais possible."
                      }
                    </div>
                  </Stack__>
                </div>
                <section
                  data-plasmic-name={"conditionsAccessibilite2"}
                  data-plasmic-override={overrides.conditionsAccessibilite2}
                  className={classNames(
                    projectcss.all,
                    sty.conditionsAccessibilite2
                  )}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"numbers3"}
                    data-plasmic-override={overrides.numbers3}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.numbers3)}
                  >
                    <Personnaliser
                      className={classNames(
                        "__wab_instance",
                        sty.personnaliser__tZyD
                      )}
                      description={
                        "Natalia est autonome r\u00e9pond aux appels, adopte le bon discours commercial, r\u00e9pond correctement \u00e0 toutes les demandes d'informations produits et aux objections."
                      }
                      img={{
                        src: "/plasmic/natalia_v_2/images/image18.png",
                        fullWidth: 86,
                        fullHeight: 86,
                        aspectRatio: undefined
                      }}
                      titre={"Autonomie compl\u00e8te"}
                    >
                      <_9042371ChatBubbleCheck1MessageIconSvgIcon
                        className={classNames(projectcss.all, sty.svg__clxLq)}
                        role={"img"}
                      />
                    </Personnaliser>
                    <Personnaliser
                      className={classNames(
                        "__wab_instance",
                        sty.personnaliser__arcAt
                      )}
                      description={
                        "Natalia analyse vos appels pour identifier les axes d'am\u00e9lioration dans vos \u00e9quipes. Un gain de temps cons\u00e9quent, le manager peut avoir une vue globale sur l'ensemble des forces de vente, ADV, secr\u00e9taires, etc."
                      }
                      img={{
                        src: "/plasmic/natalia_v_2/images/image19.png",
                        fullWidth: 86,
                        fullHeight: 86,
                        aspectRatio: undefined
                      }}
                      titre={"Supervision & Analyse"}
                    >
                      <_9989690SearchEngineInternetTechnologyResearchIconSvgIcon
                        className={classNames(projectcss.all, sty.svg__p2Sw)}
                        role={"img"}
                      />
                    </Personnaliser>
                  </Stack__>
                </section>
              </Stack__>
            </PlasmicLink__>
            <PlasmicLink__
              data-plasmic-name={"personnalisation"}
              data-plasmic-override={overrides.personnalisation}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.personnalisation
              )}
              component={Link}
              id={"personnalisation"}
              platform={"nextjs"}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__nw3AQ)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__k7WQm)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ppEPz)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__avr4Z)}
                      displayHeight={"365px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/natalia_v_2/images/promptAFuturisticBusinessEnvironmentW1Svg.svg",
                        fullWidth: 1365,
                        fullHeight: 1024,
                        aspectRatio: 1.333008
                      }}
                    />
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___4DGys)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gvCqf
                      )}
                    >
                      {"Personnalisation"}
                    </div>
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__gh3Cg
                      )}
                    >
                      {"Adaptez Natalia \u00e0 votre entreprise"}
                    </h2>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wuQ7F
                      )}
                    >
                      {
                        "Natalia r\u00e9pond \u00e0 un large \u00e9ventail de questions et elle apprend en permanence pour am\u00e9liorer l'exp\u00e9rience pour vos clients. Chaque Natalia est unique pour chaque entreprise."
                      }
                    </div>
                  </Stack__>
                </div>
                <section
                  data-plasmic-name={"conditionsPersonnalisation"}
                  data-plasmic-override={overrides.conditionsPersonnalisation}
                  className={classNames(
                    projectcss.all,
                    sty.conditionsPersonnalisation
                  )}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"numbers"}
                    data-plasmic-override={overrides.numbers}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.numbers)}
                  >
                    <Personnaliser
                      className={classNames(
                        "__wab_instance",
                        sty.personnaliser__vXu6O
                      )}
                      description={
                        "Choisissez le ton, l'humeur, la phrase d'accueil, pour une exp\u00e9rience client optimale. Nous proposons une trame t\u00e9l\u00e9phonique de r\u00e9ponse, nous vous aidons \u00e0 l'installation \u00e0 param\u00e9trer l'essentiel pour qu'elle refl\u00e8te bien l'ADN de votre entreprise."
                      }
                      titre={"Personnalisez Natalia"}
                    >
                      <_7787577SettingGearSettingsOptionsPreferencesIconSvgIcon
                        className={classNames(projectcss.all, sty.svg__wtHw)}
                        role={"img"}
                      />
                    </Personnaliser>
                    <Personnaliser
                      className={classNames(
                        "__wab_instance",
                        sty.personnaliser__g5VaH
                      )}
                      description={
                        "API avec tous vos outils m\u00e9tiers pour aller chercher ou renvoyer la bonne information. Natalia est capable de r\u00e9pondre \u00e0 une question sp\u00e9cifique sur un produit, prendre la commande et l'envoyer dans votre ERP pour traitement et pr\u00e9paration."
                      }
                      img={{
                        src: "/plasmic/natalia_v_2/images/image10.png",
                        fullWidth: 86,
                        fullHeight: 86,
                        aspectRatio: undefined
                      }}
                      titre={"Connectez vos outils m\u00e9tiers"}
                    >
                      <_8665779LinkConnectionIconSvgIcon
                        className={classNames(projectcss.all, sty.svg__lcysU)}
                        role={"img"}
                      />
                    </Personnaliser>
                  </Stack__>
                </section>
              </Stack__>
              <Partenaire
                data-plasmic-name={"partenaire"}
                data-plasmic-override={overrides.partenaire}
                className={classNames("__wab_instance", sty.partenaire)}
              />
            </PlasmicLink__>
            <BigFooter
              data-plasmic-name={"bigFooter"}
              data-plasmic-override={overrides.bigFooter}
              className={classNames("__wab_instance", sty.bigFooter)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  body: [
    "body",
    "wrapper",
    "presentation",
    "navbar",
    "h1",
    "cta",
    "cta2",
    "accessibilite",
    "conditionsAccessibilite",
    "numbers2",
    "apercu",
    "youTube",
    "tester",
    "automatisation",
    "reponsesHomogenes",
    "conditionsAccessibilite2",
    "numbers3",
    "personnalisation",
    "conditionsPersonnalisation",
    "numbers",
    "partenaire",
    "bigFooter"
  ],
  wrapper: [
    "wrapper",
    "presentation",
    "navbar",
    "h1",
    "cta",
    "cta2",
    "accessibilite",
    "conditionsAccessibilite",
    "numbers2",
    "apercu",
    "youTube",
    "tester",
    "automatisation",
    "reponsesHomogenes",
    "conditionsAccessibilite2",
    "numbers3",
    "personnalisation",
    "conditionsPersonnalisation",
    "numbers",
    "partenaire",
    "bigFooter"
  ],
  presentation: ["presentation", "navbar", "h1", "cta", "cta2"],
  navbar: ["navbar"],
  h1: ["h1"],
  cta: ["cta"],
  cta2: ["cta2"],
  accessibilite: ["accessibilite", "conditionsAccessibilite", "numbers2"],
  conditionsAccessibilite: ["conditionsAccessibilite", "numbers2"],
  numbers2: ["numbers2"],
  apercu: ["apercu", "youTube"],
  youTube: ["youTube"],
  tester: ["tester"],
  automatisation: [
    "automatisation",
    "reponsesHomogenes",
    "conditionsAccessibilite2",
    "numbers3"
  ],
  reponsesHomogenes: ["reponsesHomogenes"],
  conditionsAccessibilite2: ["conditionsAccessibilite2", "numbers3"],
  numbers3: ["numbers3"],
  personnalisation: [
    "personnalisation",
    "conditionsPersonnalisation",
    "numbers",
    "partenaire"
  ],
  conditionsPersonnalisation: ["conditionsPersonnalisation", "numbers"],
  numbers: ["numbers"],
  partenaire: ["partenaire"],
  bigFooter: ["bigFooter"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  body: "div";
  wrapper: "div";
  presentation: "section";
  navbar: typeof Navbar;
  h1: "h1";
  cta: "div";
  cta2: "div";
  accessibilite: "a";
  conditionsAccessibilite: "section";
  numbers2: "div";
  apercu: "section";
  youTube: typeof YouTube;
  tester: typeof Tester;
  automatisation: "a";
  reponsesHomogenes: "div";
  conditionsAccessibilite2: "section";
  numbers3: "div";
  personnalisation: "a";
  conditionsPersonnalisation: "section";
  numbers: "div";
  partenaire: typeof Partenaire;
  bigFooter: typeof BigFooter;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAssistanteVocale__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAssistanteVocale__VariantsArgs;
    args?: PlasmicAssistanteVocale__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicAssistanteVocale__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicAssistanteVocale__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAssistanteVocale__ArgProps,
          internalVariantPropNames: PlasmicAssistanteVocale__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAssistanteVocale__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "body") {
    func.displayName = "PlasmicAssistanteVocale";
  } else {
    func.displayName = `PlasmicAssistanteVocale.${nodeName}`;
  }
  return func;
}

export const PlasmicAssistanteVocale = Object.assign(
  // Top-level PlasmicAssistanteVocale renders the root element
  makeNodeComponent("body"),
  {
    // Helper components rendering sub-elements
    wrapper: makeNodeComponent("wrapper"),
    presentation: makeNodeComponent("presentation"),
    navbar: makeNodeComponent("navbar"),
    h1: makeNodeComponent("h1"),
    cta: makeNodeComponent("cta"),
    cta2: makeNodeComponent("cta2"),
    accessibilite: makeNodeComponent("accessibilite"),
    conditionsAccessibilite: makeNodeComponent("conditionsAccessibilite"),
    numbers2: makeNodeComponent("numbers2"),
    apercu: makeNodeComponent("apercu"),
    youTube: makeNodeComponent("youTube"),
    tester: makeNodeComponent("tester"),
    automatisation: makeNodeComponent("automatisation"),
    reponsesHomogenes: makeNodeComponent("reponsesHomogenes"),
    conditionsAccessibilite2: makeNodeComponent("conditionsAccessibilite2"),
    numbers3: makeNodeComponent("numbers3"),
    personnalisation: makeNodeComponent("personnalisation"),
    conditionsPersonnalisation: makeNodeComponent("conditionsPersonnalisation"),
    numbers: makeNodeComponent("numbers"),
    partenaire: makeNodeComponent("partenaire"),
    bigFooter: makeNodeComponent("bigFooter"),

    // Metadata about props expected for PlasmicAssistanteVocale
    internalVariantProps: PlasmicAssistanteVocale__VariantProps,
    internalArgProps: PlasmicAssistanteVocale__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Assistante Vocale IA Natalia – Répondez à tous vos appels",
      description:
        "Gagnez en réactivité avec Natalia, l’assistante vocale IA qui répond 24/7, préqualifie vos leads et désengorge vos centres d’appels.",
      ogImageSrc:
        "https://site-assets.plasmic.app/2c64147f6b26d85033032c08922d6a27.png",
      canonical: "https://getnatalia.com/assistance-vocale"
    }
  }
);

export default PlasmicAssistanteVocale;
/* prettier-ignore-end */
