/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mwhScQxahW1in9QQ9WEhLw
// Component: Svhekvnr8s8r

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Navbar from "../../Navbar"; // plasmic-import: WRD9j93d1vlf/component
import Button from "../../Button"; // plasmic-import: zBHMtY0Q_-9b/component
import YouTube from "@plasmicpkgs/react-youtube";
import BigFooter from "../../BigFooter"; // plasmic-import: fcdOVpZOWlXS/component

import { useScreenVariants as useScreenVariantsjC0Cb1S4E1Yt } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: jC0CB1S4E1YT/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: mwhScQxahW1in9QQ9WEhLw/projectcss
import sty from "./PlasmicWipTraitement.module.css"; // plasmic-import: Svhekvnr8s8r/css

import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: IC7ycYphHpjw/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: 7sgNTXN-bhFB/icon

createPlasmicElementProxy;

export type PlasmicWipTraitement__VariantMembers = {};
export type PlasmicWipTraitement__VariantsArgs = {};
type VariantPropType = keyof PlasmicWipTraitement__VariantsArgs;
export const PlasmicWipTraitement__VariantProps = new Array<VariantPropType>();

export type PlasmicWipTraitement__ArgsType = {};
type ArgPropType = keyof PlasmicWipTraitement__ArgsType;
export const PlasmicWipTraitement__ArgProps = new Array<ArgPropType>();

export type PlasmicWipTraitement__OverridesType = {
  body?: Flex__<"div">;
  wrapper?: Flex__<"div">;
  presentation?: Flex__<"section">;
  navbar?: Flex__<typeof Navbar>;
  h1?: Flex__<"h1">;
  cta?: Flex__<"div">;
  cta2?: Flex__<"div">;
  apercu?: Flex__<"section">;
  youTube?: Flex__<typeof YouTube>;
  personnaliser?: Flex__<"a"> & Partial<LinkProps>;
  optimiser?: Flex__<"a"> & Partial<LinkProps>;
  automatisation?: Flex__<"a"> & Partial<LinkProps>;
  testez?: Flex__<"section">;
  bigFooter?: Flex__<typeof BigFooter>;
};

export interface DefaultWipTraitementProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicWipTraitement__RenderFunc(props: {
  variants: PlasmicWipTraitement__VariantsArgs;
  args: PlasmicWipTraitement__ArgsType;
  overrides: PlasmicWipTraitement__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsjC0Cb1S4E1Yt()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"body"}
          data-plasmic-override={overrides.body}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.body
          )}
        >
          <div
            data-plasmic-name={"wrapper"}
            data-plasmic-override={overrides.wrapper}
            className={classNames(projectcss.all, sty.wrapper)}
          >
            <section
              data-plasmic-name={"presentation"}
              data-plasmic-override={overrides.presentation}
              className={classNames(projectcss.all, sty.presentation)}
            >
              <Navbar
                data-plasmic-name={"navbar"}
                data-plasmic-override={overrides.navbar}
                className={classNames("__wab_instance", sty.navbar)}
              />

              <h1
                data-plasmic-name={"h1"}
                data-plasmic-override={overrides.h1}
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1
                )}
              >
                {
                  "Votre assistant intelligent pour automatiser et g\u00e9rer vos commandes en toute simplicit\u00e9."
                }
              </h1>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__biF2V
                )}
              >
                {
                  "Automatisez vos processus et lib\u00e9rez vos ADV des t\u00e2ches r\u00e9p\u00e9titives pour qu'ils se concentrent sur la vente."
                }
              </div>
              <Stack__
                as={"div"}
                data-plasmic-name={"cta"}
                data-plasmic-override={overrides.cta}
                hasGap={true}
                className={classNames(projectcss.all, sty.cta)}
              >
                <Button
                  className={classNames("__wab_instance", sty.button__fFhTq)}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hsrvF
                      )}
                    >
                      {"Centraliser"}
                    </div>
                  }
                  linkTo={"#centraliser"}
                  openLinkInNewTab={false}
                />

                <Button
                  ariaLabel={``}
                  className={classNames("__wab_instance", sty.button__vYeIk)}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gzzmC
                      )}
                    >
                      {"Optimiser"}
                    </div>
                  }
                  linkTo={"#optimiser"}
                  openLinkInNewTab={false}
                />
              </Stack__>
              <div
                data-plasmic-name={"cta2"}
                data-plasmic-override={overrides.cta2}
                className={classNames(projectcss.all, sty.cta2)}
              >
                <Button
                  ariaLabel={``}
                  className={classNames("__wab_instance", sty.button__gtOuz)}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vsb12
                      )}
                    >
                      {"Automatiser"}
                    </div>
                  }
                  linkTo={"#automatiser"}
                  openLinkInNewTab={false}
                />
              </div>
            </section>
            <section
              data-plasmic-name={"apercu"}
              data-plasmic-override={overrides.apercu}
              className={classNames(projectcss.all, sty.apercu)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___59N3)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__b6Iyf
                  )}
                >
                  {"Aper\u00e7u de l'interface"}
                </h2>
                <YouTube
                  data-plasmic-name={"youTube"}
                  data-plasmic-override={overrides.youTube}
                  className={classNames("__wab_instance", sty.youTube)}
                  videoId={"R6MeLqRQzYw"}
                />
              </Stack__>
            </section>
            <PlasmicLink__
              data-plasmic-name={"personnaliser"}
              data-plasmic-override={overrides.personnaliser}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.personnaliser
              )}
              component={Link}
              id={"centraliser"}
              platform={"nextjs"}
            >
              <div className={classNames(projectcss.all, sty.freeBox__uqVcH)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___9UX32)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__bdtCr)}
                    displayHeight={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "auto"
                        : "365px"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/natalia_v_2/images/aModernCleanDashboardInterfaceDisplayingVar1Svg.svg",
                      fullWidth: 1365,
                      fullHeight: 1024,
                      aspectRatio: 1.333008
                    }}
                  />
                </div>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__fWaot)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rhNru
                    )}
                  >
                    {"Centraliser"}
                  </div>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__eY2P4
                    )}
                  >
                    {"Centralisez tous vos canaux de vente en un seul outil ! "}
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hqQd1
                    )}
                  >
                    {
                      "Natalia vous permet de g\u00e9rer efficacement vos commandes, qu'elles proviennent de votre site e-commerce, de marketplaces ou de ventes directes, le tout sur une interface simple et intuitive."
                    }
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__tYrGy)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___0K1Fu
                      )}
                    >
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__kTb7V
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__o4Cn
                          )}
                        >
                          {"\u2709\ufe0f"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__j1DQm
                          )}
                        >
                          {"Aussi simple qu'une bo\u00eete mail"}
                        </div>
                      </Stack__>
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__eT57H
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__tOh
                          )}
                        >
                          {"\ud83d\udd17"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__t4L1K
                          )}
                        >
                          {"Branchez vos sites et vos outils"}
                        </div>
                      </Stack__>
                    </Stack__>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__gLdhT)}
                    >
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__hkV9E
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___69BU3
                          )}
                        >
                          {"\u23f1\ufe0f"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ajGmi
                          )}
                        >
                          {"Op\u00e9rationnel en 20min"}
                        </div>
                      </Stack__>
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__zNes5
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__hDzuA
                          )}
                        >
                          {"\ud83d\udd12"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__bKt9
                          )}
                        >
                          {"Priv\u00e9 et s\u00e9curis\u00e9"}
                        </div>
                      </Stack__>
                    </Stack__>
                  </Stack__>
                </Stack__>
              </div>
            </PlasmicLink__>
            <PlasmicLink__
              data-plasmic-name={"optimiser"}
              data-plasmic-override={overrides.optimiser}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.optimiser
              )}
              component={Link}
              id={"accessibilite"}
              platform={"nextjs"}
            >
              <div className={classNames(projectcss.all, sty.freeBox___8Zslm)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___0NFrG)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xZl9A
                    )}
                  >
                    {"Optimiser"}
                  </div>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__kbULq
                    )}
                  >
                    {"Resaisissez automatiquement toute commande mail"}
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jctZq
                    )}
                  >
                    {
                      "Gr\u00e2ce \u00e0 son module d'IA, Natalia extrait et int\u00e8gre automatiquement toute commande re\u00e7ue par email, en analysant le contenu du message ou des pi\u00e8ces jointes."
                    }
                  </div>
                </Stack__>
                <div className={classNames(projectcss.all, sty.freeBox___0X1E)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__wGjDj)}
                    displayHeight={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "100%"
                        : "365px"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/natalia_v_2/images/aCleanModernRepresentationOfAnAiSystemPro2Svg.svg",
                      fullWidth: 1365,
                      fullHeight: 1024,
                      aspectRatio: 1.333008
                    }}
                  />
                </div>
              </div>
            </PlasmicLink__>
            <PlasmicLink__
              data-plasmic-name={"automatisation"}
              data-plasmic-override={overrides.automatisation}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.automatisation
              )}
              component={Link}
              id={"automatisation"}
              platform={"nextjs"}
            >
              <div className={classNames(projectcss.all, sty.freeBox__hnurg)}>
                <div className={classNames(projectcss.all, sty.freeBox__b7QfU)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__vxFw0)}
                    displayHeight={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "100%"
                        : "365px"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/natalia_v_2/images/anOfficeEnvironmentWithAModernSleekCompute1Svg.svg",
                      fullWidth: 1365,
                      fullHeight: 1024,
                      aspectRatio: 1.333008
                    }}
                  />
                </div>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__z0PIy)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yklnF
                    )}
                  >
                    {"Automatisation"}
                  </div>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__x0Usi
                    )}
                  >
                    {"Connectez \u00e0 votre ERP"}
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mwZ8C
                    )}
                  >
                    {
                      "Natalia est une interface sp\u00e9cialement con\u00e7ue pour s'int\u00e9grer \u00e0 votre ERP, permettant de synchroniser et de transf\u00e9rer toutes vos donn\u00e9es de mani\u00e8re fluide."
                    }
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__dPRk)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__pXiXk)}
                    >
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__evf0S
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ooeQp
                          )}
                        >
                          {"\ud83d\udcdd"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__arpEt
                          )}
                        >
                          {"Bons de commandes"}
                        </div>
                      </Stack__>
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__kqwsi
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___02FBx
                          )}
                        >
                          {"\ud83d\udce6"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__rkQmV
                          )}
                        >
                          {"Suivi des stocks"}
                        </div>
                      </Stack__>
                    </Stack__>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__iaQab)}
                    >
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__wuZfC
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__gJo7I
                          )}
                        >
                          {"\ud83d\udd0d"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__fYaiO
                          )}
                        >
                          {"Tra\u00e7abilit\u00e9 des produits"}
                        </div>
                      </Stack__>
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__u95J1
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___1G5F
                          )}
                        >
                          {"\ud83d\udc64"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__llLks
                          )}
                        >
                          {"Fiches clients"}
                        </div>
                      </Stack__>
                    </Stack__>
                  </Stack__>
                </Stack__>
              </div>
            </PlasmicLink__>
            <section
              data-plasmic-name={"testez"}
              data-plasmic-override={overrides.testez}
              className={classNames(projectcss.all, sty.testez)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__fG6Xw)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__rkDwh
                  )}
                >
                  {"Nous sommes l\u00e0 pour vous aider \ud83d\udc4d"}
                </h2>
              </Stack__>
              <Button
                className={classNames("__wab_instance", sty.button__mnC)}
                label={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__khF4Q
                    )}
                  >
                    {"Contactez-nous \u2192"}
                  </div>
                }
              />
            </section>
            <BigFooter
              data-plasmic-name={"bigFooter"}
              data-plasmic-override={overrides.bigFooter}
              className={classNames("__wab_instance", sty.bigFooter)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  body: [
    "body",
    "wrapper",
    "presentation",
    "navbar",
    "h1",
    "cta",
    "cta2",
    "apercu",
    "youTube",
    "personnaliser",
    "optimiser",
    "automatisation",
    "testez",
    "bigFooter"
  ],
  wrapper: [
    "wrapper",
    "presentation",
    "navbar",
    "h1",
    "cta",
    "cta2",
    "apercu",
    "youTube",
    "personnaliser",
    "optimiser",
    "automatisation",
    "testez",
    "bigFooter"
  ],
  presentation: ["presentation", "navbar", "h1", "cta", "cta2"],
  navbar: ["navbar"],
  h1: ["h1"],
  cta: ["cta"],
  cta2: ["cta2"],
  apercu: ["apercu", "youTube"],
  youTube: ["youTube"],
  personnaliser: ["personnaliser"],
  optimiser: ["optimiser"],
  automatisation: ["automatisation"],
  testez: ["testez"],
  bigFooter: ["bigFooter"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  body: "div";
  wrapper: "div";
  presentation: "section";
  navbar: typeof Navbar;
  h1: "h1";
  cta: "div";
  cta2: "div";
  apercu: "section";
  youTube: typeof YouTube;
  personnaliser: "a";
  optimiser: "a";
  automatisation: "a";
  testez: "section";
  bigFooter: typeof BigFooter;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicWipTraitement__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicWipTraitement__VariantsArgs;
    args?: PlasmicWipTraitement__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicWipTraitement__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicWipTraitement__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicWipTraitement__ArgProps,
          internalVariantPropNames: PlasmicWipTraitement__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicWipTraitement__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "body") {
    func.displayName = "PlasmicWipTraitement";
  } else {
    func.displayName = `PlasmicWipTraitement.${nodeName}`;
  }
  return func;
}

export const PlasmicWipTraitement = Object.assign(
  // Top-level PlasmicWipTraitement renders the root element
  makeNodeComponent("body"),
  {
    // Helper components rendering sub-elements
    wrapper: makeNodeComponent("wrapper"),
    presentation: makeNodeComponent("presentation"),
    navbar: makeNodeComponent("navbar"),
    h1: makeNodeComponent("h1"),
    cta: makeNodeComponent("cta"),
    cta2: makeNodeComponent("cta2"),
    apercu: makeNodeComponent("apercu"),
    youTube: makeNodeComponent("youTube"),
    personnaliser: makeNodeComponent("personnaliser"),
    optimiser: makeNodeComponent("optimiser"),
    automatisation: makeNodeComponent("automatisation"),
    testez: makeNodeComponent("testez"),
    bigFooter: makeNodeComponent("bigFooter"),

    // Metadata about props expected for PlasmicWipTraitement
    internalVariantProps: PlasmicWipTraitement__VariantProps,
    internalArgProps: PlasmicWipTraitement__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicWipTraitement;
/* prettier-ignore-end */
