/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mwhScQxahW1in9QQ9WEhLw
// Component: yb6NoNktLEqW

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: mwhScQxahW1in9QQ9WEhLw/projectcss
import sty from "./PlasmicChronologie.module.css"; // plasmic-import: yb6NoNktLEqW/css

import Ellipse142Icon from "./icons/PlasmicIcon__Ellipse142"; // plasmic-import: RtaTbrDxbIfz/icon
import Icon8Icon from "./icons/PlasmicIcon__Icon8"; // plasmic-import: ML31v7iBOSTD/icon

createPlasmicElementProxy;

export type PlasmicChronologie__VariantMembers = {};
export type PlasmicChronologie__VariantsArgs = {};
type VariantPropType = keyof PlasmicChronologie__VariantsArgs;
export const PlasmicChronologie__VariantProps = new Array<VariantPropType>();

export type PlasmicChronologie__ArgsType = {
  dateDroite?: string;
  descriptionDroite?: string;
  dateGauche?: string;
  descriptionGauche?: string;
};
type ArgPropType = keyof PlasmicChronologie__ArgsType;
export const PlasmicChronologie__ArgProps = new Array<ArgPropType>(
  "dateDroite",
  "descriptionDroite",
  "dateGauche",
  "descriptionGauche"
);

export type PlasmicChronologie__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultChronologieProps {
  dateDroite?: string;
  descriptionDroite?: string;
  dateGauche?: string;
  descriptionGauche?: string;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicChronologie__RenderFunc(props: {
  variants: PlasmicChronologie__VariantsArgs;
  args: PlasmicChronologie__ArgsType;
  overrides: PlasmicChronologie__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          dateDroite: "Octobre 2024",
          descriptionDroite:
            "En seulement 15 jours, ils obtiennent une assistante vocale qui fonctionne!",
          dateGauche: "Octobre 2024",
          descriptionGauche:
            "En seulement 15 jours, ils obtiennent une assistante vocale qui fonctionne!"
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__f7BeZ)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__oMidr
          )}
        >
          <React.Fragment>
            {(() => {
              try {
                return $props.dateGauche;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__kQxt0
          )}
        >
          <React.Fragment>
            {(() => {
              try {
                return $props.descriptionGauche;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__e8Ieb)}>
        <Ellipse142Icon
          className={classNames(projectcss.all, sty.svg__rui)}
          role={"img"}
        />

        <Icon8Icon
          className={classNames(projectcss.all, sty.svg__x8Ti)}
          role={"img"}
        />
      </div>
      <div className={classNames(projectcss.all, sty.freeBox___03KgM)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__fBZv
          )}
        >
          <React.Fragment>
            {(() => {
              try {
                return $props.dateDroite;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "Octobre 2024";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__uqKg
          )}
        >
          <React.Fragment>
            {(() => {
              try {
                return $props.descriptionDroite;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "En seulement 15 jours, ils obtiennent une assistante vocale qui fonctionne !";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicChronologie__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicChronologie__VariantsArgs;
    args?: PlasmicChronologie__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicChronologie__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicChronologie__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicChronologie__ArgProps,
          internalVariantPropNames: PlasmicChronologie__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicChronologie__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicChronologie";
  } else {
    func.displayName = `PlasmicChronologie.${nodeName}`;
  }
  return func;
}

export const PlasmicChronologie = Object.assign(
  // Top-level PlasmicChronologie renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicChronologie
    internalVariantProps: PlasmicChronologie__VariantProps,
    internalArgProps: PlasmicChronologie__ArgProps
  }
);

export default PlasmicChronologie;
/* prettier-ignore-end */
