/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2utUyfwAdNYhisb36rBizH
// Component: Oz4K6O9ubKeI

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 2utUyfwAdNYhisb36rBizH/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 2utUyfwAdNYhisb36rBizH/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 2utUyfwAdNYhisb36rBizH/projectcss
import sty from "./PlasmicLogo.module.css"; // plasmic-import: Oz4K6O9ubKeI/css

createPlasmicElementProxy;

export type PlasmicLogo__VariantMembers = {
  white: "white";
  smallLogo: "smallLogo";
};
export type PlasmicLogo__VariantsArgs = {
  white?: SingleBooleanChoiceArg<"white">;
  smallLogo?: SingleBooleanChoiceArg<"smallLogo">;
};
type VariantPropType = keyof PlasmicLogo__VariantsArgs;
export const PlasmicLogo__VariantProps = new Array<VariantPropType>(
  "white",
  "smallLogo"
);

export type PlasmicLogo__ArgsType = {};
type ArgPropType = keyof PlasmicLogo__ArgsType;
export const PlasmicLogo__ArgProps = new Array<ArgPropType>();

export type PlasmicLogo__OverridesType = {
  root?: Flex__<"a"> & Partial<LinkProps>;
  text?: Flex__<"div">;
};

export interface DefaultLogoProps {
  white?: SingleBooleanChoiceArg<"white">;
  smallLogo?: SingleBooleanChoiceArg<"smallLogo">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLogo__RenderFunc(props: {
  variants: PlasmicLogo__VariantsArgs;
  args: PlasmicLogo__ArgsType;
  overrides: PlasmicLogo__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "white",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.white
      },
      {
        path: "smallLogo",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.smallLogo
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <PlasmicLink__
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.a,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        { [sty.rootwhite]: hasVariant($state, "white", "white") }
      )}
      component={Link}
      href={`/`}
      platform={"nextjs"}
    >
      <PlasmicImg__
        alt={""}
        className={classNames(sty.img__aqPsM, {
          [sty.imgsmallLogo__aqPsMzCvBq]: hasVariant(
            $state,
            "smallLogo",
            "smallLogo"
          ),
          [sty.imgwhite__aqPsMVXuk]: hasVariant($state, "white", "white")
        })}
        displayHeight={
          hasVariant(globalVariants, "mobile", "mobileOnly") ? "auto" : "40px"
        }
        displayMaxHeight={"none"}
        displayMaxWidth={
          hasVariant(globalVariants, "mobile", "mobileOnly") ? "30px" : "40px"
        }
        displayMinHeight={"0"}
        displayMinWidth={"0"}
        displayWidth={
          hasVariant(globalVariants, "mobile", "mobileOnly") ? "auto" : "100%"
        }
        src={
          hasVariant($state, "smallLogo", "smallLogo")
            ? {
                src: "/plasmic/site_actuel_natalia_auto/images/logoNataliaSvg.svg",
                fullWidth: 1024,
                fullHeight: 1024,
                aspectRatio: undefined
              }
            : hasVariant(globalVariants, "mobile", "mobileOnly")
              ? {
                  src: "/plasmic/site_actuel_natalia_auto/images/logoNataliaSvg.svg",
                  fullWidth: 1024,
                  fullHeight: 1024,
                  aspectRatio: undefined
                }
              : {
                  src: "/plasmic/site_actuel_natalia_auto/images/logoNataliaSvg.svg",
                  fullWidth: 1024,
                  fullHeight: 1024,
                  aspectRatio: undefined
                }
        }
      />

      {(hasVariant($state, "smallLogo", "smallLogo") ? true : false) ? (
        <PlasmicImg__
          alt={""}
          className={classNames(sty.img__pds2F, {
            [sty.imgsmallLogo__pds2FzCvBq]: hasVariant(
              $state,
              "smallLogo",
              "smallLogo"
            ),
            [sty.imgwhite__pds2FVXuk]: hasVariant($state, "white", "white")
          })}
          displayHeight={
            hasVariant(globalVariants, "mobile", "mobileOnly") ? "auto" : "40px"
          }
          displayMaxHeight={"none"}
          displayMaxWidth={
            hasVariant($state, "smallLogo", "smallLogo")
              ? "50px"
              : hasVariant(globalVariants, "mobile", "mobileOnly")
                ? "30px"
                : "40px"
          }
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={
            hasVariant(globalVariants, "mobile", "mobileOnly") ? "auto" : "100%"
          }
          src={
            hasVariant($state, "smallLogo", "smallLogo")
              ? {
                  src: "/plasmic/site_actuel_natalia_auto/images/captureDecran20250818A165622Png.png",
                  fullWidth: 142,
                  fullHeight: 148,
                  aspectRatio: undefined
                }
              : hasVariant(globalVariants, "mobile", "mobileOnly")
                ? {
                    src: "/plasmic/site_actuel_natalia_auto/images/logoNataliaSvg.svg",
                    fullWidth: 1024,
                    fullHeight: 1024,
                    aspectRatio: undefined
                  }
                : {
                    src: "/plasmic/site_actuel_natalia_auto/images/logoNataliaSvg.svg",
                    fullWidth: 1024,
                    fullHeight: 1024,
                    aspectRatio: undefined
                  }
          }
        />
      ) : null}
      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text, {
          [sty.textsmallLogo]: hasVariant($state, "smallLogo", "smallLogo"),
          [sty.textwhite]: hasVariant($state, "white", "white")
        })}
      >
        {hasVariant($state, "white", "white") ? (
          "NATALIA"
        ) : (
          <React.Fragment>
            <span
              className={"plasmic_default__all plasmic_default__span"}
              style={{ color: "#252729" }}
            >
              {"NATALIA"}
            </span>
          </React.Fragment>
        )}
      </div>
    </PlasmicLink__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "text"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "a";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLogo__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLogo__VariantsArgs;
    args?: PlasmicLogo__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicLogo__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicLogo__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLogo__ArgProps,
          internalVariantPropNames: PlasmicLogo__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLogo__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLogo";
  } else {
    func.displayName = `PlasmicLogo.${nodeName}`;
  }
  return func;
}

export const PlasmicLogo = Object.assign(
  // Top-level PlasmicLogo renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicLogo
    internalVariantProps: PlasmicLogo__VariantProps,
    internalArgProps: PlasmicLogo__ArgProps
  }
);

export default PlasmicLogo;
/* prettier-ignore-end */
