/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2utUyfwAdNYhisb36rBizH
// Component: ma5qxHUh6erM

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Navbar from "../../Navbar"; // plasmic-import: F0Go0DR6--TF/component
import ButtonPrimary from "../../ButtonPrimary"; // plasmic-import: TU5A2-p6WFJJ/component
import Probleme from "../../Probleme"; // plasmic-import: MXIUXB0YnmeL/component
import CetaitAvant from "../../CetaitAvant"; // plasmic-import: fEr4e8g2uhL6/component
import Solution from "../../Solution"; // plasmic-import: vAcwOvnOFNI4/component
import CasDusage from "../../CasDusage"; // plasmic-import: mUYvgEuGkieL/component
import Avantages from "../../Avantages"; // plasmic-import: x2T3E4Kio9_Z/component
import Footer from "../../Footer"; // plasmic-import: Mvxx80XtzO5S/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 2utUyfwAdNYhisb36rBizH/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 2utUyfwAdNYhisb36rBizH/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 2utUyfwAdNYhisb36rBizH/projectcss
import sty from "./PlasmicCentresDappel.module.css"; // plasmic-import: ma5qxHUh6erM/css

import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: ViTHihoGnbR-/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: BAVaBjl9jJEK/icon
import ExchangePersonelSvgrepoComSvg2Icon from "./icons/PlasmicIcon__ExchangePersonelSvgrepoComSvg2"; // plasmic-import: 560pCDFRMbfl/icon
import HourglassActiveSvgrepoComSvg2Icon from "./icons/PlasmicIcon__HourglassActiveSvgrepoComSvg2"; // plasmic-import: 2GUMrOklntnw/icon
import ShapesSvgrepoComSvg2Icon from "./icons/PlasmicIcon__ShapesSvgrepoComSvg2"; // plasmic-import: QnRQhDpwpqwS/icon
import TurnOffSvgrepoComSvg2Icon from "./icons/PlasmicIcon__TurnOffSvgrepoComSvg2"; // plasmic-import: 6bWOBRx7cC6W/icon
import DelaySvgrepoComSvgIcon from "./icons/PlasmicIcon__DelaySvgrepoComSvg"; // plasmic-import: O4W-2UqGZ8Hj/icon
import Icon18Icon from "./icons/PlasmicIcon__Icon18"; // plasmic-import: EM09k3C8nJ6k/icon
import Rocket02SvgrepoComSvgIcon from "./icons/PlasmicIcon__Rocket02SvgrepoComSvg"; // plasmic-import: 3tAt5428l_Lv/icon
import ConnectionSvgrepoCom1SvgIcon from "./icons/PlasmicIcon__ConnectionSvgrepoCom1Svg"; // plasmic-import: bvtyxBHeKgBl/icon
import CalendarLinesPenSvgrepoComSvgIcon from "./icons/PlasmicIcon__CalendarLinesPenSvgrepoComSvg"; // plasmic-import: kNemrl--N6SP/icon
import MoneyCheckDollarPenSvgrepoComSvgIcon from "./icons/PlasmicIcon__MoneyCheckDollarPenSvgrepoComSvg"; // plasmic-import: SJKU4Ll6kih5/icon
import CallDroppedSvgrepoComSvg3Icon from "./icons/PlasmicIcon__CallDroppedSvgrepoComSvg3"; // plasmic-import: D7d2-6s6ivWF/icon
import Icon10Icon from "./icons/PlasmicIcon__Icon10"; // plasmic-import: 2Xaj6978lnhC/icon
import Icon11Icon from "./icons/PlasmicIcon__Icon11"; // plasmic-import: uJO-DE32SArw/icon

createPlasmicElementProxy;

export type PlasmicCentresDappel__VariantMembers = {};
export type PlasmicCentresDappel__VariantsArgs = {};
type VariantPropType = keyof PlasmicCentresDappel__VariantsArgs;
export const PlasmicCentresDappel__VariantProps = new Array<VariantPropType>();

export type PlasmicCentresDappel__ArgsType = {};
type ArgPropType = keyof PlasmicCentresDappel__ArgsType;
export const PlasmicCentresDappel__ArgProps = new Array<ArgPropType>();

export type PlasmicCentresDappel__OverridesType = {
  body?: Flex__<"div">;
  wrapper?: Flex__<"section">;
  navbar?: Flex__<typeof Navbar>;
  hero?: Flex__<"section">;
  h1?: Flex__<"h1">;
  chiffre?: Flex__<"section">;
  douleur2?: Flex__<"section">;
  chiffre2?: Flex__<"section">;
  section?: Flex__<"section">;
  headerHeroSection?: Flex__<"div">;
  cetaitAvant?: Flex__<typeof CetaitAvant>;
  solutions?: Flex__<"section">;
  outilsMetiers?: Flex__<"section">;
  nextlane?: Flex__<"div">;
  cdKglobal?: Flex__<"div">;
  dcSnet?: Flex__<"div">;
  bee2Link?: Flex__<"div">;
  columns?: Flex__<"div">;
  casUsage?: Flex__<"section">;
  titre?: Flex__<"div">;
  casOld?: Flex__<"div">;
  callToAction?: Flex__<"section">;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultCentresDappelProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCentresDappel__RenderFunc(props: {
  variants: PlasmicCentresDappel__VariantsArgs;
  args: PlasmicCentresDappel__ArgsType;
  overrides: PlasmicCentresDappel__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicCentresDappel.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicCentresDappel.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicCentresDappel.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicCentresDappel.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicCentresDappel.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicCentresDappel.pageMetadata.description}
        />

        <link
          rel="canonical"
          href={PlasmicCentresDappel.pageMetadata.canonical}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"body"}
          data-plasmic-override={overrides.body}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.body
          )}
        >
          <section
            data-plasmic-name={"wrapper"}
            data-plasmic-override={overrides.wrapper}
            className={classNames(projectcss.all, sty.wrapper)}
          >
            <Navbar
              data-plasmic-name={"navbar"}
              data-plasmic-override={overrides.navbar}
              className={classNames("__wab_instance", sty.navbar)}
            />

            <section
              data-plasmic-name={"hero"}
              data-plasmic-override={overrides.hero}
              className={classNames(projectcss.all, sty.hero)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__ziSm9)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___1VdNy)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox___5Jl8C)}
                  >
                    <h1
                      data-plasmic-name={"h1"}
                      data-plasmic-override={overrides.h1}
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1
                      )}
                    >
                      {"Natalia r\u00e9pond, "}
                    </h1>
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2___14Qql
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#1E3A8A00" }}
                        >
                          {"transf\u00e8re et assiste"}
                        </span>
                      </React.Fragment>
                    </h2>
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__zibom
                      )}
                    >
                      {"vos clients 24/7"}
                    </h2>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fUiXl
                    )}
                  >
                    {hasVariant(globalVariants, "mobile", "mobileOnly") ? (
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{
                            color: "var(--token-okZqvxZ_nx_g)",
                            fontWeight: 700
                          }}
                        >
                          {
                            "Une voix naturelle, une compr\u00e9hension instantan\u00e9e et une int\u00e9gration fluide \u00e0 votre centre d\u2019appels"
                          }
                        </span>
                      </React.Fragment>
                    ) : (
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{
                            color: "var(--token-okZqvxZ_nx_g)",
                            fontWeight: 700
                          }}
                        >
                          {
                            "Une voix naturelle, une compr\u00e9hension instantan\u00e9e et une int\u00e9gration fluide \u00e0 votre centre d\u2019appels"
                          }
                        </span>
                      </React.Fragment>
                    )}
                  </div>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link___8SgCr
                    )}
                    component={Link}
                    href={`/contact`}
                    platform={"nextjs"}
                  >
                    <ButtonPrimary
                      className={classNames(
                        "__wab_instance",
                        sty.buttonPrimary__zrKVi
                      )}
                      label={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__nraPm
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "#FFFFFF" }}
                            >
                              {"R\u00e9server une d\u00e9mo"}
                            </span>
                          </React.Fragment>
                        </div>
                      }
                    />
                  </PlasmicLink__>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__adEtn)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__xk0M)}
                    displayHeight={
                      hasVariant(globalVariants, "mobile", "mobileOnly")
                        ? "100%"
                        : "100%"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/site_actuel_natalia_auto/images/centreDappelsPng2.png",
                      fullWidth: 1004,
                      fullHeight: 744,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
            </section>
            <section
              data-plasmic-name={"chiffre"}
              data-plasmic-override={overrides.chiffre}
              className={classNames(projectcss.all, sty.chiffre)}
            >
              <h3
                className={classNames(
                  projectcss.all,
                  projectcss.h3,
                  projectcss.__wab_text,
                  sty.h3__s73Up
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "var(--token-okZqvxZ_nx_g)" }}
                  >
                    {
                      "L'IA est un enjeu majeur pour les centres d'appels dans les mois et ann\u00e9es \u00e0 venir. "
                    }
                  </span>
                  <React.Fragment>{"\n"}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "var(--token-okZqvxZ_nx_g)" }}
                  >
                    {
                      "Pour rester comp\u00e9titif, vous devez proposez des solutions adapt\u00e9es \u00e0 vos clients. "
                    }
                  </span>
                </React.Fragment>
              </h3>
            </section>
            <section
              data-plasmic-name={"douleur2"}
              data-plasmic-override={overrides.douleur2}
              className={classNames(projectcss.all, sty.douleur2)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__wdwmv)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__u4YXx
                  )}
                >
                  {"Vos probl\u00e8mes..."}
                </h2>
                <div className={classNames(projectcss.all, sty.freeBox__kzIWq)}>
                  <Probleme
                    className={classNames(
                      "__wab_instance",
                      sty.probleme__ng8Sl
                    )}
                    descr={
                      "C'est un m\u00e9tier \u00e9prouvant pour vos \u00e9quipes, vous avez du turnover et devez sans cesse recruter et reformer \u00e0 nouveau."
                    }
                    nom={"Turnover important"}
                  >
                    <ExchangePersonelSvgrepoComSvg2Icon
                      className={classNames(projectcss.all, sty.svg___6OLn1)}
                      role={"img"}
                    />
                  </Probleme>
                  <Probleme
                    className={classNames(
                      "__wab_instance",
                      sty.probleme__oZppc
                    )}
                    descr={
                      "Malgr\u00e9 un plan de charge millim\u00e9tr\u00e9, vous ne pouvez pas faire face aux impr\u00e9vus et scaler votre capacit\u00e9 d'appels au dernier moment..."
                    }
                    nom={"Temps d'attente"}
                  >
                    <HourglassActiveSvgrepoComSvg2Icon
                      className={classNames(projectcss.all, sty.svg__dNceQ)}
                      role={"img"}
                    />
                  </Probleme>
                  <Probleme
                    className={classNames(
                      "__wab_instance",
                      sty.probleme__o1AIo
                    )}
                    descr={
                      "Votre qualit\u00e9 de r\u00e9ponse n'est pas toujours optimale, vous avez d\u00fb mal \u00e0 standardiser malgr\u00e9 les process en place."
                    }
                    nom={"H\u00e9t\u00e9rog\u00e9n\u00e9it\u00e9"}
                  >
                    <ShapesSvgrepoComSvg2Icon
                      className={classNames(projectcss.all, sty.svg__oZw27)}
                      role={"img"}
                    />
                  </Probleme>
                  <Probleme
                    className={classNames(
                      "__wab_instance",
                      sty.probleme__awAUx
                    )}
                    descr={
                      "Entre les pics d'appels, les heures ferm\u00e9es, les week-ends, les vacances, il est difficile d'\u00eatre toujours disponible pour vos clients"
                    }
                    nom={"Indisponibilit\u00e9s"}
                  >
                    <TurnOffSvgrepoComSvg2Icon
                      className={classNames(projectcss.all, sty.svg__sJmWx)}
                      role={"img"}
                    />
                  </Probleme>
                </div>
              </div>
            </section>
            <section
              data-plasmic-name={"chiffre2"}
              data-plasmic-override={overrides.chiffre2}
              className={classNames(projectcss.all, sty.chiffre2)}
            >
              <h3
                className={classNames(
                  projectcss.all,
                  projectcss.h3,
                  projectcss.__wab_text,
                  sty.h3__mV5Pq
                )}
              >
                {hasVariant(globalVariants, "mobile", "mobileOnly")
                  ? "Malgr\u00e9 vos efforts, votre organisation a ses limites et vos co\u00fbts fixes plombent la rentabilit\u00e9..."
                  : "Malgr\u00e9 vos efforts, votre organisation a ses limites et \nvos co\u00fbts fixes plombent la rentabilit\u00e9..."}
              </h3>
            </section>
            <section
              data-plasmic-name={"section"}
              data-plasmic-override={overrides.section}
              className={classNames(projectcss.all, sty.section)}
            >
              <div
                data-plasmic-name={"headerHeroSection"}
                data-plasmic-override={overrides.headerHeroSection}
                className={classNames(projectcss.all, sty.headerHeroSection)}
              />
            </section>
            <CetaitAvant
              data-plasmic-name={"cetaitAvant"}
              data-plasmic-override={overrides.cetaitAvant}
              className={classNames("__wab_instance", sty.cetaitAvant)}
            />

            <section
              data-plasmic-name={"solutions"}
              data-plasmic-override={overrides.solutions}
              className={classNames(projectcss.all, sty.solutions)}
            >
              <div className={classNames(projectcss.all, sty.freeBox___0EyGu)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__lpfEh
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "var(--token-okZqvxZ_nx_g)" }}
                    >
                      {"Nos solutions"}
                    </span>
                  </React.Fragment>
                </h2>
                <div className={classNames(projectcss.all, sty.freeBox__vj9AS)}>
                  <Solution
                    className={classNames(
                      "__wab_instance",
                      sty.solution__t8O4Z
                    )}
                    descr={
                      "Apportez de la disponiblit\u00e9 et donc de la flexibilit\u00e9 \u00e0 votre organisation. 24h/24, 7j/7 pour g\u00e9rer les appels, les astreintes, les vacances, jours f\u00e9ri\u00e9s, etc..."
                    }
                    img={{
                      src: "/plasmic/site_actuel_natalia_auto/images/missedCallSvgrepoComSvg.svg",
                      fullWidth: 800,
                      fullHeight: 800,
                      aspectRatio: undefined
                    }}
                    nom={"Disponible"}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__mqC6U)}
                    >
                      <DelaySvgrepoComSvgIcon
                        className={classNames(projectcss.all, sty.svg__tMloI)}
                        role={"img"}
                      />
                    </div>
                  </Solution>
                  <Solution
                    className={classNames(
                      "__wab_instance",
                      sty.solution__wFjQe
                    )}
                    descr={
                      "Notre accompagnement s'adapte \u00e0 vos besoins, ce n'est pas un outil standard sur \u00e9tag\u00e8re qui ne correspond pas \u00e0 votre cahier des charges."
                    }
                    img={{
                      src: "/plasmic/site_actuel_natalia_auto/images/businessCashManagementSvgrepoComSvg.svg",
                      fullWidth: 800,
                      fullHeight: 800,
                      aspectRatio: undefined
                    }}
                    nom={"Personnalis\u00e9e"}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__wUDuP)}
                    >
                      <Icon18Icon
                        className={classNames(projectcss.all, sty.svg__v8YBb)}
                        role={"img"}
                      />
                    </div>
                  </Solution>
                  <Solution
                    className={classNames(
                      "__wab_instance",
                      sty.solution__kisfl
                    )}
                    descr={
                      "Nous pouvons mettre une capacit\u00e9 de 100 appels en parall\u00e8le, ou plus, selon vos besoins, de quoi g\u00e9rer les impr\u00e9vus et les pics d'appels. Augmentez votre capacit\u00e9 d'appels sans exploser vos co\u00fbts."
                    }
                    img={{
                      src: "/plasmic/site_actuel_natalia_auto/images/hourglassActiveSvgrepoComSvg.svg",
                      fullWidth: 800,
                      fullHeight: 800,
                      aspectRatio: undefined
                    }}
                    nom={"Scalable"}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__t3Eqz)}
                    >
                      <Rocket02SvgrepoComSvgIcon
                        className={classNames(projectcss.all, sty.svg__zcSkT)}
                        role={"img"}
                      />
                    </div>
                  </Solution>
                  <Solution
                    className={classNames(
                      "__wab_instance",
                      sty.solution__fpZhX
                    )}
                    descr={
                      "Connect\u00e9e \u00e0 vos outils m\u00e9tiers, Natalia remonte les flux au bon endroit au bon moment pour vous faire gagner du temps de saisi r\u00e9p\u00e9titif et chronophage."
                    }
                    img={{
                      src: "/plasmic/site_actuel_natalia_auto/images/businessGrowthManagementSvgrepoComSvg.svg",
                      fullWidth: 800,
                      fullHeight: 800,
                      aspectRatio: undefined
                    }}
                    nom={"Int\u00e9gr\u00e9e"}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__h8WIt)}
                    >
                      <ConnectionSvgrepoCom1SvgIcon
                        className={classNames(projectcss.all, sty.svg__aq7L6)}
                        role={"img"}
                      />
                    </div>
                  </Solution>
                </div>
              </div>
            </section>
            <section
              data-plasmic-name={"outilsMetiers"}
              data-plasmic-override={overrides.outilsMetiers}
              className={classNames(projectcss.all, sty.outilsMetiers)}
            >
              <div className={classNames(projectcss.all, sty.freeBox___83O1G)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__bzvbt
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{
                        color: "var(--token-okZqvxZ_nx_g)",
                        fontWeight: 700
                      }}
                    >
                      {"Natalia est compatible "}
                    </span>
                  </React.Fragment>
                </h2>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__mykWv
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700, color: "transparent" }}
                    >
                      {"avec tous vos outils m\u00e9tiers"}
                    </span>
                  </React.Fragment>
                </h2>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___5RopH)}>
                <div
                  data-plasmic-name={"nextlane"}
                  data-plasmic-override={overrides.nextlane}
                  className={classNames(projectcss.all, sty.nextlane)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___7Byxd)}
                    displayHeight={
                      hasVariant(globalVariants, "mobile", "mobileOnly")
                        ? "100px"
                        : "30%"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "mobile", "mobileOnly")
                        ? "none"
                        : "50%"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/site_actuel_natalia_auto/images/ciscoLogoBlue2016SvgPng.png",
                      fullWidth: 2560,
                      fullHeight: 1352,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div
                  data-plasmic-name={"cdKglobal"}
                  data-plasmic-override={overrides.cdKglobal}
                  className={classNames(projectcss.all, sty.cdKglobal)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__kyl3T)}
                    displayHeight={
                      hasVariant(globalVariants, "mobile", "mobileOnly")
                        ? "100px"
                        : "200px"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "mobile", "mobileOnly")
                        ? "auto"
                        : "298px"
                    }
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/site_actuel_natalia_auto/images/_3CxLogoWinePng.png",
                      fullWidth: 3000,
                      fullHeight: 2000,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div
                  data-plasmic-name={"dcSnet"}
                  data-plasmic-override={overrides.dcSnet}
                  className={classNames(projectcss.all, sty.dcSnet)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__hXsDd)}
                    displayHeight={
                      hasVariant(globalVariants, "mobile", "mobileOnly")
                        ? "100px"
                        : "auto"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/site_actuel_natalia_auto/images/manifoneLogo2Png.png",
                      fullWidth: 312,
                      fullHeight: 169,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div
                  data-plasmic-name={"bee2Link"}
                  data-plasmic-override={overrides.bee2Link}
                  className={classNames(projectcss.all, sty.bee2Link)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__xfHm)}
                    displayHeight={
                      hasVariant(globalVariants, "mobile", "mobileOnly")
                        ? "100px"
                        : "77.52%"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "mobile", "mobileOnly")
                        ? "100%"
                        : "100%"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "mobile", "mobileOnly")
                        ? "100%"
                        : "107.22%"
                    }
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/site_actuel_natalia_auto/images/vocalcomPartenaireLandingPng.png",
                      fullWidth: 356,
                      fullHeight: 150,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"columns"}
                data-plasmic-override={overrides.columns}
                className={classNames(projectcss.all, sty.columns)}
              >
                <div className={classNames(projectcss.all, sty.column__klnWd)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__cTqK)}
                    displayHeight={"70%"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/site_actuel_natalia_auto/images/captureDEcran20250820A093226RemovebgPreviewPng.png",
                      fullWidth: 700,
                      fullHeight: 202,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__ya0CD)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__fqMdH)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/site_actuel_natalia_auto/images/eyJidWNrZxQiOiJwYxj0BmVycGFnZs5Wcm9KIiwia2V5IjoibWVkaWEvY29UdGFjdF9PbWFnZxMvZmU1NzBiNwEtYjQxZc00Ndq0LTkyZtMtNwMyNdFiYwQwMwYxLzYwYzI5ZDg5LtRlMTgtNdVjMs05MDczLwu3ZmVlZDgwZwIyZc5WbmciLcJlZGl0CyI6EyJ0B0ZvPng.png",
                      fullWidth: 974,
                      fullHeight: 256,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__cRG1)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___6Yuj)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/site_actuel_natalia_auto/images/logoMpaPng.png",
                      fullWidth: 282,
                      fullHeight: 100,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__lQMdf)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__geJxL)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "mobile", "mobileOnly")
                        ? "40%"
                        : "50%"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={
                      hasVariant(globalVariants, "mobile", "mobileOnly")
                        ? {
                            src: "/plasmic/site_actuel_natalia_auto/images/captureDEcran20250820A093431RemovebgPreviewPng.png",
                            fullWidth: 452,
                            fullHeight: 418,
                            aspectRatio: undefined
                          }
                        : {
                            src: "/plasmic/site_actuel_natalia_auto/images/captureDEcran20250820A093431RemovebgPreviewPng.png",
                            fullWidth: 452,
                            fullHeight: 418,
                            aspectRatio: undefined
                          }
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__tRx9S)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__dlSjq)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "mobile", "mobileOnly")
                        ? "90%"
                        : "100%"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/site_actuel_natalia_auto/images/captureDEcran20250820A093312RemovebgPreviewPng.png",
                      fullWidth: 672,
                      fullHeight: 220,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
            </section>
            <section
              data-plasmic-name={"casUsage"}
              data-plasmic-override={overrides.casUsage}
              className={classNames(projectcss.all, sty.casUsage)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__wpX4)}>
                <div
                  data-plasmic-name={"titre"}
                  data-plasmic-override={overrides.titre}
                  className={classNames(projectcss.all, sty.titre)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__ieNzy
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-okZqvxZ_nx_g)" }}
                      >
                        {"Cas d'usage concrets"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__moJJ
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-okZqvxZ_nx_g)" }}
                      >
                        {
                          "L'objectif n'est pas de remplacer l'humain en concession mais de l'"
                        }
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{
                          fontWeight: 700,
                          color: "var(--token-okZqvxZ_nx_g)"
                        }}
                      >
                        {
                          "assister pour qu'il se concentre sur les missions \u00e0 forte valeur ajout\u00e9e"
                        }
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-okZqvxZ_nx_g)" }}
                      >
                        {
                          ". Ici avec ces 4 cas d'usage, nous r\u00e9pondons \u00e0 "
                        }
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{
                          fontWeight: 700,
                          color: "var(--token-okZqvxZ_nx_g)"
                        }}
                      >
                        {"80% des besoins en appels entrants en concessions."}
                      </span>
                    </React.Fragment>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__j9Pf8)}>
                  <CasDusage
                    className={classNames(
                      "__wab_instance",
                      sty.casDusage__wkl4H
                    )}
                    description={
                      "Connect\u00e9e \u00e0 votre calendrier m\u00e9tier, type Service Box ou MecaPlanning, Natalia propose des cr\u00e9neaux, valide avec le client et renseigne les informations directement sur le logiciel."
                    }
                    titre={"Prise de RDV atelier"}
                  >
                    <CalendarLinesPenSvgrepoComSvgIcon
                      className={classNames(projectcss.all, sty.svg__dzXfp)}
                      role={"img"}
                    />
                  </CasDusage>
                  <CasDusage
                    className={classNames(
                      "__wab_instance",
                      sty.casDusage__yfFVg
                    )}
                    description={
                      "Natalia est disponible 24h/24, 7j/7, elle prend donc en charge 100% des demandes entrants y compris les leads. Durant l'\u00e9change, elle qualifie le besoin et renvoie les informations au service concern\u00e9."
                    }
                    titre={"Qualifier les leads entrants"}
                  >
                    <MoneyCheckDollarPenSvgrepoComSvgIcon
                      className={classNames(projectcss.all, sty.svg__kgcVl)}
                      role={"img"}
                    />
                  </CasDusage>
                  <CasDusage
                    className={classNames(
                      "__wab_instance",
                      sty.casDusage__fwJla
                    )}
                    description={
                      "20% des appels en concession sont des appels \u00e0 transf\u00e9rer, cela prend du temps, casse la productivit\u00e9 de vos \u00e9quipes et n'apporte pas de r\u00e9elle valeur ajout\u00e9e."
                    }
                    titre={"Transfert d'appels"}
                  >
                    <CallDroppedSvgrepoComSvg3Icon
                      className={classNames(projectcss.all, sty.svg___03DoX)}
                      role={"img"}
                    />
                  </CasDusage>
                  <CasDusage
                    className={classNames(
                      "__wab_instance",
                      sty.casDusage__pozq4
                    )}
                    description={
                      "R\u00e9ponse aux demandes r\u00e9currentes \u00e0 partir de votre base de connaissance. Natalia s'enrichit des \u00e9changes dans le temps pour \u00eatre de plus en plus pertinente."
                    }
                    titre={"Demandes g\u00e9n\u00e9rales"}
                  >
                    <Rocket02SvgrepoComSvgIcon
                      className={classNames(projectcss.all, sty.svg__eTnr6)}
                      role={"img"}
                    />
                  </CasDusage>
                </div>
                <div
                  data-plasmic-name={"casOld"}
                  data-plasmic-override={overrides.casOld}
                  className={classNames(projectcss.all, sty.casOld)}
                >
                  <Avantages
                    className={classNames(
                      "__wab_instance",
                      sty.avantages__glry
                    )}
                  />

                  <Avantages
                    className={classNames(
                      "__wab_instance",
                      sty.avantages__ql18V
                    )}
                    description={
                      "Natalia est disponible 24h/24, 7j/7, elle prend donc en charge 100% des demandes entrants y compris les leads. Durant l'\u00e9change, elle qualifie le besoin et renvoie les informations au service concern\u00e9."
                    }
                    jaune={true}
                    titre={"Qualifier les leads entrants"}
                  >
                    <MoneyCheckDollarPenSvgrepoComSvgIcon
                      className={classNames(projectcss.all, sty.svg__dutvm)}
                      role={"img"}
                    />
                  </Avantages>
                  <Avantages
                    className={classNames(
                      "__wab_instance",
                      sty.avantages___2U7Jh
                    )}
                    description={
                      "20% des appels en concession sont des appels \u00e0 transf\u00e9rer, cela prend du temps, casse la productivit\u00e9 de vos \u00e9quipes et n'apporte pas de r\u00e9elle valeur ajout\u00e9e."
                    }
                    titre={"Transfert d'appels"}
                  >
                    <Icon10Icon
                      className={classNames(projectcss.all, sty.svg__qc7Ux)}
                      role={"img"}
                    />
                  </Avantages>
                  <Avantages
                    className={classNames(
                      "__wab_instance",
                      sty.avantages___4UbrH
                    )}
                    description={
                      "R\u00e9ponse aux demandes r\u00e9currentes \u00e0 partir de votre base de connaissance. Natalia s'enrichit des \u00e9changes dans le temps pour \u00eatre de plus en plus pertinente."
                    }
                    jaune={true}
                    titre={"Demandes g\u00e9n\u00e9rales"}
                  >
                    <Icon11Icon
                      className={classNames(projectcss.all, sty.svg__c4F3N)}
                      role={"img"}
                    />
                  </Avantages>
                </div>
              </div>
            </section>
            <section
              data-plasmic-name={"callToAction"}
              data-plasmic-override={overrides.callToAction}
              className={classNames(projectcss.all, sty.callToAction)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__rwlTk
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {
                      "Nous d\u00e9finissons ensemble le cadre du pilote lors d'un premier rendez-vous."
                    }
                  </span>
                </React.Fragment>
              </h2>
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__sgbkd
                )}
                component={Link}
                href={`/contact`}
                platform={"nextjs"}
              >
                <ButtonPrimary
                  className={classNames(
                    "__wab_instance",
                    sty.buttonPrimary__xB5Ma
                  )}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___4HszD
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#FFFFFF" }}
                        >
                          {"R\u00e9server une d\u00e9mo"}
                        </span>
                      </React.Fragment>
                    </div>
                  }
                />
              </PlasmicLink__>
            </section>
            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />
          </section>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  body: [
    "body",
    "wrapper",
    "navbar",
    "hero",
    "h1",
    "chiffre",
    "douleur2",
    "chiffre2",
    "section",
    "headerHeroSection",
    "cetaitAvant",
    "solutions",
    "outilsMetiers",
    "nextlane",
    "cdKglobal",
    "dcSnet",
    "bee2Link",
    "columns",
    "casUsage",
    "titre",
    "casOld",
    "callToAction",
    "footer"
  ],
  wrapper: [
    "wrapper",
    "navbar",
    "hero",
    "h1",
    "chiffre",
    "douleur2",
    "chiffre2",
    "section",
    "headerHeroSection",
    "cetaitAvant",
    "solutions",
    "outilsMetiers",
    "nextlane",
    "cdKglobal",
    "dcSnet",
    "bee2Link",
    "columns",
    "casUsage",
    "titre",
    "casOld",
    "callToAction",
    "footer"
  ],
  navbar: ["navbar"],
  hero: ["hero", "h1"],
  h1: ["h1"],
  chiffre: ["chiffre"],
  douleur2: ["douleur2"],
  chiffre2: ["chiffre2"],
  section: ["section", "headerHeroSection"],
  headerHeroSection: ["headerHeroSection"],
  cetaitAvant: ["cetaitAvant"],
  solutions: ["solutions"],
  outilsMetiers: [
    "outilsMetiers",
    "nextlane",
    "cdKglobal",
    "dcSnet",
    "bee2Link",
    "columns"
  ],
  nextlane: ["nextlane"],
  cdKglobal: ["cdKglobal"],
  dcSnet: ["dcSnet"],
  bee2Link: ["bee2Link"],
  columns: ["columns"],
  casUsage: ["casUsage", "titre", "casOld"],
  titre: ["titre"],
  casOld: ["casOld"],
  callToAction: ["callToAction"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  body: "div";
  wrapper: "section";
  navbar: typeof Navbar;
  hero: "section";
  h1: "h1";
  chiffre: "section";
  douleur2: "section";
  chiffre2: "section";
  section: "section";
  headerHeroSection: "div";
  cetaitAvant: typeof CetaitAvant;
  solutions: "section";
  outilsMetiers: "section";
  nextlane: "div";
  cdKglobal: "div";
  dcSnet: "div";
  bee2Link: "div";
  columns: "div";
  casUsage: "section";
  titre: "div";
  casOld: "div";
  callToAction: "section";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCentresDappel__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCentresDappel__VariantsArgs;
    args?: PlasmicCentresDappel__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicCentresDappel__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicCentresDappel__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCentresDappel__ArgProps,
          internalVariantPropNames: PlasmicCentresDappel__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCentresDappel__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "body") {
    func.displayName = "PlasmicCentresDappel";
  } else {
    func.displayName = `PlasmicCentresDappel.${nodeName}`;
  }
  return func;
}

export const PlasmicCentresDappel = Object.assign(
  // Top-level PlasmicCentresDappel renders the root element
  makeNodeComponent("body"),
  {
    // Helper components rendering sub-elements
    wrapper: makeNodeComponent("wrapper"),
    navbar: makeNodeComponent("navbar"),
    hero: makeNodeComponent("hero"),
    h1: makeNodeComponent("h1"),
    chiffre: makeNodeComponent("chiffre"),
    douleur2: makeNodeComponent("douleur2"),
    chiffre2: makeNodeComponent("chiffre2"),
    section: makeNodeComponent("section"),
    headerHeroSection: makeNodeComponent("headerHeroSection"),
    cetaitAvant: makeNodeComponent("cetaitAvant"),
    solutions: makeNodeComponent("solutions"),
    outilsMetiers: makeNodeComponent("outilsMetiers"),
    nextlane: makeNodeComponent("nextlane"),
    cdKglobal: makeNodeComponent("cdKglobal"),
    dcSnet: makeNodeComponent("dcSnet"),
    bee2Link: makeNodeComponent("bee2Link"),
    columns: makeNodeComponent("columns"),
    casUsage: makeNodeComponent("casUsage"),
    titre: makeNodeComponent("titre"),
    casOld: makeNodeComponent("casOld"),
    callToAction: makeNodeComponent("callToAction"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicCentresDappel
    internalVariantProps: PlasmicCentresDappel__VariantProps,
    internalArgProps: PlasmicCentresDappel__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Natalia, l’assistante IA qui automatise vos appels.",
      description:
        "Disponibilité 24/7, réponses instantanées et homogènes. Ne laissez plus aucun client sans réponse !",
      ogImageSrc: "",
      canonical: "https//getnatalia.com/centre-d-appel"
    }
  }
);

export default PlasmicCentresDappel;
/* prettier-ignore-end */
