/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2utUyfwAdNYhisb36rBizH
// Component: vFP5wSB0nDuM

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 2utUyfwAdNYhisb36rBizH/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 2utUyfwAdNYhisb36rBizH/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 2utUyfwAdNYhisb36rBizH/projectcss
import sty from "./PlasmicDesignKitNavigationHeaderDirectLink.module.css"; // plasmic-import: vFP5wSB0nDuM/css

import IcnArrowLinkIcon from "./icons/PlasmicIcon__IcnArrowLink"; // plasmic-import: zKsSExY-USuh/icon

createPlasmicElementProxy;

export type PlasmicDesignKitNavigationHeaderDirectLink__VariantMembers = {
  colorMode: "dark" | "light";
  isLoginLink: "isLoginLink";
  withBorder: "withBorder";
};
export type PlasmicDesignKitNavigationHeaderDirectLink__VariantsArgs = {
  colorMode?: SingleChoiceArg<"dark" | "light">;
  isLoginLink?: SingleBooleanChoiceArg<"isLoginLink">;
  withBorder?: SingleBooleanChoiceArg<"withBorder">;
};
type VariantPropType =
  keyof PlasmicDesignKitNavigationHeaderDirectLink__VariantsArgs;
export const PlasmicDesignKitNavigationHeaderDirectLink__VariantProps =
  new Array<VariantPropType>("colorMode", "isLoginLink", "withBorder");

export type PlasmicDesignKitNavigationHeaderDirectLink__ArgsType = {
  text?: string;
  openInNewTab?: Target;
  dataTrkciamCategory?: string;
  dataTrkciamAction?: string;
  dataTrkciamName?: string;
  destination?: string;
};
type ArgPropType = keyof PlasmicDesignKitNavigationHeaderDirectLink__ArgsType;
export const PlasmicDesignKitNavigationHeaderDirectLink__ArgProps =
  new Array<ArgPropType>(
    "text",
    "openInNewTab",
    "dataTrkciamCategory",
    "dataTrkciamAction",
    "dataTrkciamName",
    "destination"
  );

export type PlasmicDesignKitNavigationHeaderDirectLink__OverridesType = {
  navItem?: Flex__<"div">;
  link?: Flex__<"a"> & Partial<LinkProps>;
  bgHover?: Flex__<"div">;
  text?: Flex__<"div">;
  svg?: Flex__<"svg">;
};

export interface DefaultDesignKitNavigationHeaderDirectLinkProps {
  text?: string;
  openInNewTab?: Target;
  dataTrkciamCategory?: string;
  dataTrkciamAction?: string;
  dataTrkciamName?: string;
  destination?: string;
  colorMode?: SingleChoiceArg<"dark" | "light">;
  isLoginLink?: SingleBooleanChoiceArg<"isLoginLink">;
  withBorder?: SingleBooleanChoiceArg<"withBorder">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicDesignKitNavigationHeaderDirectLink__RenderFunc(props: {
  variants: PlasmicDesignKitNavigationHeaderDirectLink__VariantsArgs;
  args: PlasmicDesignKitNavigationHeaderDirectLink__ArgsType;
  overrides: PlasmicDesignKitNavigationHeaderDirectLink__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          text: "Menu name"
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "colorMode",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.colorMode
      },
      {
        path: "isLoginLink",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.isLoginLink
      },
      {
        path: "withBorder",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.withBorder
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const [isNavItemHover, triggerNavItemHoverProps] = useTrigger("useHover", {});
  const triggers = {
    hover_navItem: isNavItemHover
  };

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"navItem"}
      data-plasmic-override={overrides.navItem}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.navItem,
        {
          [sty.navItemcolorMode_light]: hasVariant(
            $state,
            "colorMode",
            "light"
          ),
          [sty.navItemisLoginLink]: hasVariant(
            $state,
            "isLoginLink",
            "isLoginLink"
          ),
          [sty.navItemwithBorder]: hasVariant(
            $state,
            "withBorder",
            "withBorder"
          )
        }
      )}
      data-plasmic-trigger-props={[triggerNavItemHoverProps]}
    >
      <PlasmicLink__
        data-plasmic-name={"link"}
        data-plasmic-override={overrides.link}
        className={classNames(projectcss.all, projectcss.a, sty.link, {
          [sty.linkcolorMode_light]: hasVariant($state, "colorMode", "light"),
          [sty.linkisLoginLink]: hasVariant(
            $state,
            "isLoginLink",
            "isLoginLink"
          ),
          [sty.linkwithBorder]: hasVariant($state, "withBorder", "withBorder")
        })}
        component={Link}
        data-trkciam-action={args.dataTrkciamAction}
        data-trkciam-category={args.dataTrkciamCategory}
        data-trkciam-name={args.dataTrkciamName}
        href={args.destination}
        platform={"nextjs"}
        target={args.openInNewTab}
      >
        {(
          triggers.hover_navItem &&
          hasVariant(globalVariants, "mobile", "mobileOnly")
            ? true
            : triggers.hover_navItem
              ? true
              : false
        ) ? (
          <div
            data-plasmic-name={"bgHover"}
            data-plasmic-override={overrides.bgHover}
            className={classNames(projectcss.all, sty.bgHover, {
              [sty.bgHovercolorMode_light]: hasVariant(
                $state,
                "colorMode",
                "light"
              )
            })}
          />
        ) : null}
        <div
          data-plasmic-name={"text"}
          data-plasmic-override={overrides.text}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text,
            {
              [sty.textcolorMode_light]: hasVariant(
                $state,
                "colorMode",
                "light"
              ),
              [sty.textwithBorder]: hasVariant(
                $state,
                "withBorder",
                "withBorder"
              )
            }
          )}
        >
          <React.Fragment>
            {(() => {
              try {
                return $props.text;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </div>
        {(
          hasVariant($state, "isLoginLink", "isLoginLink") &&
          hasVariant(globalVariants, "mobile", "mobileOnly")
            ? true
            : false
        ) ? (
          <IcnArrowLinkIcon
            data-plasmic-name={"svg"}
            data-plasmic-override={overrides.svg}
            className={classNames(projectcss.all, sty.svg, {
              [sty.svgisLoginLink]: hasVariant(
                $state,
                "isLoginLink",
                "isLoginLink"
              )
            })}
            role={"img"}
          />
        ) : null}
      </PlasmicLink__>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  navItem: ["navItem", "link", "bgHover", "text", "svg"],
  link: ["link", "bgHover", "text", "svg"],
  bgHover: ["bgHover"],
  text: ["text"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  navItem: "div";
  link: "a";
  bgHover: "div";
  text: "div";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDesignKitNavigationHeaderDirectLink__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDesignKitNavigationHeaderDirectLink__VariantsArgs;
    args?: PlasmicDesignKitNavigationHeaderDirectLink__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<
      PlasmicDesignKitNavigationHeaderDirectLink__VariantsArgs,
      ReservedPropsType
    > &
    // Specify args directly as props
    Omit<
      PlasmicDesignKitNavigationHeaderDirectLink__ArgsType,
      ReservedPropsType
    > &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames:
            PlasmicDesignKitNavigationHeaderDirectLink__ArgProps,
          internalVariantPropNames:
            PlasmicDesignKitNavigationHeaderDirectLink__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicDesignKitNavigationHeaderDirectLink__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "navItem") {
    func.displayName = "PlasmicDesignKitNavigationHeaderDirectLink";
  } else {
    func.displayName = `PlasmicDesignKitNavigationHeaderDirectLink.${nodeName}`;
  }
  return func;
}

export const PlasmicDesignKitNavigationHeaderDirectLink = Object.assign(
  // Top-level PlasmicDesignKitNavigationHeaderDirectLink renders the root element
  makeNodeComponent("navItem"),
  {
    // Helper components rendering sub-elements
    link: makeNodeComponent("link"),
    bgHover: makeNodeComponent("bgHover"),
    text: makeNodeComponent("text"),
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicDesignKitNavigationHeaderDirectLink
    internalVariantProps:
      PlasmicDesignKitNavigationHeaderDirectLink__VariantProps,
    internalArgProps: PlasmicDesignKitNavigationHeaderDirectLink__ArgProps
  }
);

export default PlasmicDesignKitNavigationHeaderDirectLink;
/* prettier-ignore-end */
