/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2utUyfwAdNYhisb36rBizH
// Component: JtOPDUnSJGAf

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 2utUyfwAdNYhisb36rBizH/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 2utUyfwAdNYhisb36rBizH/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 2utUyfwAdNYhisb36rBizH/projectcss
import sty from "./PlasmicMep2.module.css"; // plasmic-import: JtOPDUnSJGAf/css

import OneSquareFillSvgrepoComSvgIcon from "./icons/PlasmicIcon__OneSquareFillSvgrepoComSvg"; // plasmic-import: 0xZ7nxKvcQGv/icon

createPlasmicElementProxy;

export type PlasmicMep2__VariantMembers = {};
export type PlasmicMep2__VariantsArgs = {};
type VariantPropType = keyof PlasmicMep2__VariantsArgs;
export const PlasmicMep2__VariantProps = new Array<VariantPropType>();

export type PlasmicMep2__ArgsType = {
  nbr?: React.ComponentProps<typeof PlasmicImg__>["src"];
  nom?: string;
  desc?: string;
  children?: React.ReactNode;
};
type ArgPropType = keyof PlasmicMep2__ArgsType;
export const PlasmicMep2__ArgProps = new Array<ArgPropType>(
  "nbr",
  "nom",
  "desc",
  "children"
);

export type PlasmicMep2__OverridesType = {
  root?: Flex__<"div">;
  h4?: Flex__<"h4">;
  h6?: Flex__<"h6">;
};

export interface DefaultMep2Props {
  nbr?: React.ComponentProps<typeof PlasmicImg__>["src"];
  nom?: string;
  desc?: string;
  children?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicMep2__RenderFunc(props: {
  variants: PlasmicMep2__VariantsArgs;
  args: PlasmicMep2__ArgsType;
  overrides: PlasmicMep2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          nbr: {
            src: "/plasmic/site_actuel_natalia_auto/images/oneSquareFillSvgrepoComSvg2.svg",
            fullWidth: 800,
            fullHeight: 800,
            aspectRatio: undefined
          },
          nom: "Premier RDV",
          desc: "D\u00e9finition du besoin et du ROI attendu du projet"
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      {renderPlasmicSlot({
        defaultContents: (
          <OneSquareFillSvgrepoComSvgIcon
            className={classNames(projectcss.all, sty.svg__kA0F)}
            role={"img"}
          />
        ),

        value: args.children,
        className: classNames(sty.slotTargetChildren)
      })}
      <h4
        data-plasmic-name={"h4"}
        data-plasmic-override={overrides.h4}
        className={classNames(
          projectcss.all,
          projectcss.h4,
          projectcss.__wab_text,
          sty.h4
        )}
      >
        <React.Fragment>
          {(() => {
            try {
              return $props.nom;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return "Premier RDV";
              }
              throw e;
            }
          })()}
        </React.Fragment>
      </h4>
      <h6
        data-plasmic-name={"h6"}
        data-plasmic-override={overrides.h6}
        className={classNames(
          projectcss.all,
          projectcss.h6,
          projectcss.__wab_text,
          sty.h6
        )}
      >
        <React.Fragment>
          {(() => {
            try {
              return $props.desc;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return "D\u00e9finition du besoin et du ROI attendu du projet";
              }
              throw e;
            }
          })()}
        </React.Fragment>
      </h6>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "h4", "h6"],
  h4: ["h4"],
  h6: ["h6"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  h4: "h4";
  h6: "h6";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMep2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMep2__VariantsArgs;
    args?: PlasmicMep2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicMep2__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicMep2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMep2__ArgProps,
          internalVariantPropNames: PlasmicMep2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMep2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMep2";
  } else {
    func.displayName = `PlasmicMep2.${nodeName}`;
  }
  return func;
}

export const PlasmicMep2 = Object.assign(
  // Top-level PlasmicMep2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h4: makeNodeComponent("h4"),
    h6: makeNodeComponent("h6"),

    // Metadata about props expected for PlasmicMep2
    internalVariantProps: PlasmicMep2__VariantProps,
    internalArgProps: PlasmicMep2__ArgProps
  }
);

export default PlasmicMep2;
/* prettier-ignore-end */
