/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2utUyfwAdNYhisb36rBizH
// Component: 3SaqGLR5zIc2

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Navbar from "../../Navbar"; // plasmic-import: F0Go0DR6--TF/component
import Douleur from "../../Douleur"; // plasmic-import: zA_FXdXmlcww/component
import CetaitAvant from "../../CetaitAvant"; // plasmic-import: fEr4e8g2uhL6/component
import ReponseInstantanee from "../../ReponseInstantanee"; // plasmic-import: D59wyvXukSBr/component
import Compatibilite from "../../Compatibilite"; // plasmic-import: VS65WCIbfT4k/component
import CasDusage from "../../CasDusage"; // plasmic-import: DEERfIH_GZWU/component
import CallToAction from "../../CallToAction"; // plasmic-import: 1u9NEqdr08SU/component
import YouTube from "@plasmicpkgs/react-youtube";
import Section from "../../Section"; // plasmic-import: 7WxeGP9tABGT/component
import PriceCard from "../../PriceCard"; // plasmic-import: VgtGYFzvbs7V/component
import FooterSection from "../../FooterSection"; // plasmic-import: Mvxx80XtzO5S/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 2utUyfwAdNYhisb36rBizH/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 2utUyfwAdNYhisb36rBizH/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 2utUyfwAdNYhisb36rBizH/projectcss
import sty from "./PlasmicAutomobile.module.css"; // plasmic-import: 3SaqGLR5zIc2/css

createPlasmicElementProxy;

export type PlasmicAutomobile__VariantMembers = {};
export type PlasmicAutomobile__VariantsArgs = {};
type VariantPropType = keyof PlasmicAutomobile__VariantsArgs;
export const PlasmicAutomobile__VariantProps = new Array<VariantPropType>();

export type PlasmicAutomobile__ArgsType = {};
type ArgPropType = keyof PlasmicAutomobile__ArgsType;
export const PlasmicAutomobile__ArgProps = new Array<ArgPropType>();

export type PlasmicAutomobile__OverridesType = {
  body?: Flex__<"div">;
  wrapper?: Flex__<"section">;
  navbar?: Flex__<typeof Navbar>;
  section?: Flex__<"section">;
  headerHeroSection?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  douleur?: Flex__<typeof Douleur>;
  cetaitAvant?: Flex__<typeof CetaitAvant>;
  reponseInstantanee?: Flex__<typeof ReponseInstantanee>;
  compatibilite?: Flex__<typeof Compatibilite>;
  casDusage?: Flex__<typeof CasDusage>;
  callToAction?: Flex__<typeof CallToAction>;
  youTube?: Flex__<typeof YouTube>;
  pricingSection?: Flex__<typeof Section>;
  columns?: Flex__<"div">;
  text?: Flex__<"div">;
  footerSection?: Flex__<typeof FooterSection>;
};

export interface DefaultAutomobileProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAutomobile__RenderFunc(props: {
  variants: PlasmicAutomobile__VariantsArgs;
  args: PlasmicAutomobile__ArgsType;
  overrides: PlasmicAutomobile__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicAutomobile.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicAutomobile.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicAutomobile.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicAutomobile.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicAutomobile.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicAutomobile.pageMetadata.description}
        />

        <link rel="canonical" href={PlasmicAutomobile.pageMetadata.canonical} />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"body"}
          data-plasmic-override={overrides.body}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.body
          )}
        >
          <section
            data-plasmic-name={"wrapper"}
            data-plasmic-override={overrides.wrapper}
            className={classNames(projectcss.all, sty.wrapper)}
          >
            <Navbar
              data-plasmic-name={"navbar"}
              data-plasmic-override={overrides.navbar}
              className={classNames("__wab_instance", sty.navbar)}
            />

            <section
              data-plasmic-name={"section"}
              data-plasmic-override={overrides.section}
              className={classNames(projectcss.all, sty.section)}
            >
              <div
                data-plasmic-name={"headerHeroSection"}
                data-plasmic-override={overrides.headerHeroSection}
                className={classNames(projectcss.all, sty.headerHeroSection)}
              >
                <PlasmicImg__
                  data-plasmic-name={"img"}
                  data-plasmic-override={overrides.img}
                  alt={""}
                  className={classNames(sty.img)}
                  displayHeight={
                    hasVariant(globalVariants, "mobile", "mobileOnly")
                      ? "145px"
                      : "300px"
                  }
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/site_actuel_natalia_auto/images/chatGptImage20Aout2025103615Png.png",
                    fullWidth: 1536,
                    fullHeight: 1024,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </section>
            <Douleur
              data-plasmic-name={"douleur"}
              data-plasmic-override={overrides.douleur}
              className={classNames("__wab_instance", sty.douleur)}
            />

            <CetaitAvant
              data-plasmic-name={"cetaitAvant"}
              data-plasmic-override={overrides.cetaitAvant}
              className={classNames("__wab_instance", sty.cetaitAvant)}
            />

            <ReponseInstantanee
              data-plasmic-name={"reponseInstantanee"}
              data-plasmic-override={overrides.reponseInstantanee}
              className={classNames("__wab_instance", sty.reponseInstantanee)}
            />

            <Compatibilite
              data-plasmic-name={"compatibilite"}
              data-plasmic-override={overrides.compatibilite}
              className={classNames("__wab_instance", sty.compatibilite)}
            />

            <CasDusage
              data-plasmic-name={"casDusage"}
              data-plasmic-override={overrides.casDusage}
              className={classNames("__wab_instance", sty.casDusage)}
            />

            <CallToAction
              data-plasmic-name={"callToAction"}
              data-plasmic-override={overrides.callToAction}
              className={classNames("__wab_instance", sty.callToAction)}
            />

            <YouTube
              data-plasmic-name={"youTube"}
              data-plasmic-override={overrides.youTube}
              className={classNames("__wab_instance", sty.youTube)}
              videoId={"R6MeLqRQzYw"}
            />

            <Section
              data-plasmic-name={"pricingSection"}
              data-plasmic-override={overrides.pricingSection}
              className={classNames("__wab_instance", sty.pricingSection)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__bSbmw)}>
                <div
                  data-plasmic-name={"columns"}
                  data-plasmic-override={overrides.columns}
                  className={classNames(projectcss.all, sty.columns)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__tpFqn)}
                  >
                    <PriceCard
                      borders={["flatLeft"]}
                      className={classNames(
                        "__wab_instance",
                        sty.priceCard__zeBlb
                      )}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__ezUeC)}
                  >
                    <PriceCard
                      borders={["flatCenter"]}
                      className={classNames(
                        "__wab_instance",
                        sty.priceCard__natff
                      )}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__rj3Xl)}
                    >
                      <div
                        data-plasmic-name={"text"}
                        data-plasmic-override={overrides.text}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text
                        )}
                      >
                        {hasVariant(globalVariants, "mobile", "mobileOnly")
                          ? "We Recommended"
                          : "We Recommended"}
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__fyYd8)}
                  >
                    <PriceCard
                      borders={["flatRight"]}
                      className={classNames(
                        "__wab_instance",
                        sty.priceCard___9EUi
                      )}
                    />
                  </div>
                </div>
              </div>
            </Section>
            <FooterSection
              data-plasmic-name={"footerSection"}
              data-plasmic-override={overrides.footerSection}
              className={classNames("__wab_instance", sty.footerSection)}
            />
          </section>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  body: [
    "body",
    "wrapper",
    "navbar",
    "section",
    "headerHeroSection",
    "img",
    "douleur",
    "cetaitAvant",
    "reponseInstantanee",
    "compatibilite",
    "casDusage",
    "callToAction",
    "youTube",
    "pricingSection",
    "columns",
    "text",
    "footerSection"
  ],
  wrapper: [
    "wrapper",
    "navbar",
    "section",
    "headerHeroSection",
    "img",
    "douleur",
    "cetaitAvant",
    "reponseInstantanee",
    "compatibilite",
    "casDusage",
    "callToAction",
    "youTube",
    "pricingSection",
    "columns",
    "text",
    "footerSection"
  ],
  navbar: ["navbar"],
  section: ["section", "headerHeroSection", "img"],
  headerHeroSection: ["headerHeroSection", "img"],
  img: ["img"],
  douleur: ["douleur"],
  cetaitAvant: ["cetaitAvant"],
  reponseInstantanee: ["reponseInstantanee"],
  compatibilite: ["compatibilite"],
  casDusage: ["casDusage"],
  callToAction: ["callToAction"],
  youTube: ["youTube"],
  pricingSection: ["pricingSection", "columns", "text"],
  columns: ["columns", "text"],
  text: ["text"],
  footerSection: ["footerSection"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  body: "div";
  wrapper: "section";
  navbar: typeof Navbar;
  section: "section";
  headerHeroSection: "div";
  img: typeof PlasmicImg__;
  douleur: typeof Douleur;
  cetaitAvant: typeof CetaitAvant;
  reponseInstantanee: typeof ReponseInstantanee;
  compatibilite: typeof Compatibilite;
  casDusage: typeof CasDusage;
  callToAction: typeof CallToAction;
  youTube: typeof YouTube;
  pricingSection: typeof Section;
  columns: "div";
  text: "div";
  footerSection: typeof FooterSection;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAutomobile__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAutomobile__VariantsArgs;
    args?: PlasmicAutomobile__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicAutomobile__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicAutomobile__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAutomobile__ArgProps,
          internalVariantPropNames: PlasmicAutomobile__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAutomobile__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "body") {
    func.displayName = "PlasmicAutomobile";
  } else {
    func.displayName = `PlasmicAutomobile.${nodeName}`;
  }
  return func;
}

export const PlasmicAutomobile = Object.assign(
  // Top-level PlasmicAutomobile renders the root element
  makeNodeComponent("body"),
  {
    // Helper components rendering sub-elements
    wrapper: makeNodeComponent("wrapper"),
    navbar: makeNodeComponent("navbar"),
    section: makeNodeComponent("section"),
    headerHeroSection: makeNodeComponent("headerHeroSection"),
    img: makeNodeComponent("img"),
    douleur: makeNodeComponent("douleur"),
    cetaitAvant: makeNodeComponent("cetaitAvant"),
    reponseInstantanee: makeNodeComponent("reponseInstantanee"),
    compatibilite: makeNodeComponent("compatibilite"),
    casDusage: makeNodeComponent("casDusage"),
    callToAction: makeNodeComponent("callToAction"),
    youTube: makeNodeComponent("youTube"),
    pricingSection: makeNodeComponent("pricingSection"),
    columns: makeNodeComponent("columns"),
    text: makeNodeComponent("text"),
    footerSection: makeNodeComponent("footerSection"),

    // Metadata about props expected for PlasmicAutomobile
    internalVariantProps: PlasmicAutomobile__VariantProps,
    internalArgProps: PlasmicAutomobile__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Natalia, l’assistante IA qui automatise vos appels.",
      description:
        "Disponibilité 24/7, réponses instantanées et homogènes. Ne laissez plus aucun client sans réponse !",
      ogImageSrc: "",
      canonical: "https//getnatalia.com/"
    }
  }
);

export default PlasmicAutomobile;
/* prettier-ignore-end */
