/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2utUyfwAdNYhisb36rBizH
// Component: VS65WCIbfT4k

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 2utUyfwAdNYhisb36rBizH/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 2utUyfwAdNYhisb36rBizH/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 2utUyfwAdNYhisb36rBizH/projectcss
import sty from "./PlasmicOutilsMetiers.module.css"; // plasmic-import: VS65WCIbfT4k/css

createPlasmicElementProxy;

export type PlasmicOutilsMetiers__VariantMembers = {};
export type PlasmicOutilsMetiers__VariantsArgs = {};
type VariantPropType = keyof PlasmicOutilsMetiers__VariantsArgs;
export const PlasmicOutilsMetiers__VariantProps = new Array<VariantPropType>();

export type PlasmicOutilsMetiers__ArgsType = {};
type ArgPropType = keyof PlasmicOutilsMetiers__ArgsType;
export const PlasmicOutilsMetiers__ArgProps = new Array<ArgPropType>();

export type PlasmicOutilsMetiers__OverridesType = {
  compatibilite?: Flex__<"section">;
  h3?: Flex__<"h3">;
  nextlane?: Flex__<"div">;
  cdKglobal?: Flex__<"div">;
  mecaplanning?: Flex__<"div">;
  dcSnet?: Flex__<"div">;
  bee2Link?: Flex__<"div">;
  columns?: Flex__<"div">;
};

export interface DefaultOutilsMetiersProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicOutilsMetiers__RenderFunc(props: {
  variants: PlasmicOutilsMetiers__VariantsArgs;
  args: PlasmicOutilsMetiers__ArgsType;
  overrides: PlasmicOutilsMetiers__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <section
      data-plasmic-name={"compatibilite"}
      data-plasmic-override={overrides.compatibilite}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.compatibilite
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__yooJd)}>
        <h3
          data-plasmic-name={"h3"}
          data-plasmic-override={overrides.h3}
          className={classNames(
            projectcss.all,
            projectcss.h3,
            projectcss.__wab_text,
            sty.h3
          )}
        >
          <React.Fragment>
            <span
              className={"plasmic_default__all plasmic_default__span"}
              style={{ color: "var(--token-okZqvxZ_nx_g)", fontWeight: 700 }}
            >
              {"Natalia est compatible avec tous vos outils m\u00e9tiers"}
            </span>
          </React.Fragment>
        </h3>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__tRq3G)}>
        <div
          data-plasmic-name={"nextlane"}
          data-plasmic-override={overrides.nextlane}
          className={classNames(projectcss.all, sty.nextlane)}
        >
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__fxxVx)}
            displayHeight={"70%"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: "/plasmic/site_actuel_natalia_auto/images/captureDEcran20250820A093226RemovebgPreviewPng.png",
              fullWidth: 700,
              fullHeight: 202,
              aspectRatio: undefined
            }}
          />
        </div>
        <div
          data-plasmic-name={"cdKglobal"}
          data-plasmic-override={overrides.cdKglobal}
          className={classNames(projectcss.all, sty.cdKglobal)}
        >
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__d8PyN)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: "/plasmic/site_actuel_natalia_auto/images/eyJidWNrZxQiOiJwYxj0BmVycGFnZs5Wcm9KIiwia2V5IjoibWVkaWEvY29UdGFjdF9PbWFnZxMvZmU1NzBiNwEtYjQxZc00Ndq0LTkyZtMtNwMyNdFiYwQwMwYxLzYwYzI5ZDg5LtRlMTgtNdVjMs05MDczLwu3ZmVlZDgwZwIyZc5WbmciLcJlZGl0CyI6EyJ0B0ZvPng.png",
              fullWidth: 974,
              fullHeight: 256,
              aspectRatio: undefined
            }}
          />
        </div>
        <div
          data-plasmic-name={"mecaplanning"}
          data-plasmic-override={overrides.mecaplanning}
          className={classNames(projectcss.all, sty.mecaplanning)}
        >
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img___1QYi)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: "/plasmic/site_actuel_natalia_auto/images/logoMpaPng.png",
              fullWidth: 282,
              fullHeight: 100,
              aspectRatio: undefined
            }}
          />
        </div>
        <div
          data-plasmic-name={"dcSnet"}
          data-plasmic-override={overrides.dcSnet}
          className={classNames(projectcss.all, sty.dcSnet)}
        >
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img___7LlI2)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={
              hasVariant(globalVariants, "mobile", "mobileOnly") ? "40%" : "50%"
            }
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={
              hasVariant(globalVariants, "mobile", "mobileOnly")
                ? {
                    src: "/plasmic/site_actuel_natalia_auto/images/captureDEcran20250820A093431RemovebgPreviewPng.png",
                    fullWidth: 452,
                    fullHeight: 418,
                    aspectRatio: undefined
                  }
                : {
                    src: "/plasmic/site_actuel_natalia_auto/images/captureDEcran20250820A093431RemovebgPreviewPng.png",
                    fullWidth: 452,
                    fullHeight: 418,
                    aspectRatio: undefined
                  }
            }
          />
        </div>
        <div
          data-plasmic-name={"bee2Link"}
          data-plasmic-override={overrides.bee2Link}
          className={classNames(projectcss.all, sty.bee2Link)}
        >
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__iL7P9)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={
              hasVariant(globalVariants, "mobile", "mobileOnly")
                ? "90%"
                : "100%"
            }
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: "/plasmic/site_actuel_natalia_auto/images/captureDEcran20250820A093312RemovebgPreviewPng.png",
              fullWidth: 672,
              fullHeight: 220,
              aspectRatio: undefined
            }}
          />
        </div>
      </div>
      <div
        data-plasmic-name={"columns"}
        data-plasmic-override={overrides.columns}
        className={classNames(projectcss.all, sty.columns)}
      >
        <div className={classNames(projectcss.all, sty.column___7KLlX)}>
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__rFbRc)}
            displayHeight={"70%"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: "/plasmic/site_actuel_natalia_auto/images/captureDEcran20250820A093226RemovebgPreviewPng.png",
              fullWidth: 700,
              fullHeight: 202,
              aspectRatio: undefined
            }}
          />
        </div>
        <div className={classNames(projectcss.all, sty.column___2YcDr)}>
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__a9MGp)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: "/plasmic/site_actuel_natalia_auto/images/eyJidWNrZxQiOiJwYxj0BmVycGFnZs5Wcm9KIiwia2V5IjoibWVkaWEvY29UdGFjdF9PbWFnZxMvZmU1NzBiNwEtYjQxZc00Ndq0LTkyZtMtNwMyNdFiYwQwMwYxLzYwYzI5ZDg5LtRlMTgtNdVjMs05MDczLwu3ZmVlZDgwZwIyZc5WbmciLcJlZGl0CyI6EyJ0B0ZvPng.png",
              fullWidth: 974,
              fullHeight: 256,
              aspectRatio: undefined
            }}
          />
        </div>
        <div className={classNames(projectcss.all, sty.column__l1Ig9)}>
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img___09WLw)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: "/plasmic/site_actuel_natalia_auto/images/logoMpaPng.png",
              fullWidth: 282,
              fullHeight: 100,
              aspectRatio: undefined
            }}
          />
        </div>
        <div className={classNames(projectcss.all, sty.column__bO5WZ)}>
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__xqYw4)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={
              hasVariant(globalVariants, "mobile", "mobileOnly") ? "40%" : "50%"
            }
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={
              hasVariant(globalVariants, "mobile", "mobileOnly")
                ? {
                    src: "/plasmic/site_actuel_natalia_auto/images/captureDEcran20250820A093431RemovebgPreviewPng.png",
                    fullWidth: 452,
                    fullHeight: 418,
                    aspectRatio: undefined
                  }
                : {
                    src: "/plasmic/site_actuel_natalia_auto/images/captureDEcran20250820A093431RemovebgPreviewPng.png",
                    fullWidth: 452,
                    fullHeight: 418,
                    aspectRatio: undefined
                  }
            }
          />
        </div>
        <div className={classNames(projectcss.all, sty.column__n3Sj1)}>
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img___42BTx)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={
              hasVariant(globalVariants, "mobile", "mobileOnly")
                ? "90%"
                : "100%"
            }
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: "/plasmic/site_actuel_natalia_auto/images/captureDEcran20250820A093312RemovebgPreviewPng.png",
              fullWidth: 672,
              fullHeight: 220,
              aspectRatio: undefined
            }}
          />
        </div>
      </div>
    </section>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  compatibilite: [
    "compatibilite",
    "h3",
    "nextlane",
    "cdKglobal",
    "mecaplanning",
    "dcSnet",
    "bee2Link",
    "columns"
  ],
  h3: ["h3"],
  nextlane: ["nextlane"],
  cdKglobal: ["cdKglobal"],
  mecaplanning: ["mecaplanning"],
  dcSnet: ["dcSnet"],
  bee2Link: ["bee2Link"],
  columns: ["columns"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  compatibilite: "section";
  h3: "h3";
  nextlane: "div";
  cdKglobal: "div";
  mecaplanning: "div";
  dcSnet: "div";
  bee2Link: "div";
  columns: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicOutilsMetiers__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicOutilsMetiers__VariantsArgs;
    args?: PlasmicOutilsMetiers__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicOutilsMetiers__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicOutilsMetiers__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicOutilsMetiers__ArgProps,
          internalVariantPropNames: PlasmicOutilsMetiers__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicOutilsMetiers__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "compatibilite") {
    func.displayName = "PlasmicOutilsMetiers";
  } else {
    func.displayName = `PlasmicOutilsMetiers.${nodeName}`;
  }
  return func;
}

export const PlasmicOutilsMetiers = Object.assign(
  // Top-level PlasmicOutilsMetiers renders the root element
  makeNodeComponent("compatibilite"),
  {
    // Helper components rendering sub-elements
    h3: makeNodeComponent("h3"),
    nextlane: makeNodeComponent("nextlane"),
    cdKglobal: makeNodeComponent("cdKglobal"),
    mecaplanning: makeNodeComponent("mecaplanning"),
    dcSnet: makeNodeComponent("dcSnet"),
    bee2Link: makeNodeComponent("bee2Link"),
    columns: makeNodeComponent("columns"),

    // Metadata about props expected for PlasmicOutilsMetiers
    internalVariantProps: PlasmicOutilsMetiers__VariantProps,
    internalArgProps: PlasmicOutilsMetiers__ArgProps
  }
);

export default PlasmicOutilsMetiers;
/* prettier-ignore-end */
