/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2utUyfwAdNYhisb36rBizH
// Component: 1u9NEqdr08SU

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import CloudIamNavigationLinkPrimaryCta from "../../CloudIamNavigationLinkPrimaryCta"; // plasmic-import: HiVfgKFJx8Th/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 2utUyfwAdNYhisb36rBizH/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 2utUyfwAdNYhisb36rBizH/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 2utUyfwAdNYhisb36rBizH/projectcss
import sty from "./PlasmicCallToAction.module.css"; // plasmic-import: 1u9NEqdr08SU/css

createPlasmicElementProxy;

export type PlasmicCallToAction__VariantMembers = {};
export type PlasmicCallToAction__VariantsArgs = {};
type VariantPropType = keyof PlasmicCallToAction__VariantsArgs;
export const PlasmicCallToAction__VariantProps = new Array<VariantPropType>();

export type PlasmicCallToAction__ArgsType = {};
type ArgPropType = keyof PlasmicCallToAction__ArgsType;
export const PlasmicCallToAction__ArgProps = new Array<ArgPropType>();

export type PlasmicCallToAction__OverridesType = {
  callToAction?: Flex__<"section">;
  freeBox?: Flex__<"div">;
  cloudIamNavigationLinkPrimaryCta?: Flex__<
    typeof CloudIamNavigationLinkPrimaryCta
  >;
  text?: Flex__<"div">;
};

export interface DefaultCallToActionProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCallToAction__RenderFunc(props: {
  variants: PlasmicCallToAction__VariantsArgs;
  args: PlasmicCallToAction__ArgsType;
  overrides: PlasmicCallToAction__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <section
      data-plasmic-name={"callToAction"}
      data-plasmic-override={overrides.callToAction}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.callToAction
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        <h3
          className={classNames(
            projectcss.all,
            projectcss.h3,
            projectcss.__wab_text,
            sty.h3__dd3Ko
          )}
        >
          {hasVariant(globalVariants, "mobile", "mobileOnly") ? (
            <React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#1E3A8A", fontWeight: 700 }}
              >
                {
                  "Il est temps de r\u00e9pondre \u00e0 100% des appels entrants"
                }
              </span>
            </React.Fragment>
          ) : (
            <React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#1E3A8A", fontWeight: 700 }}
              >
                {
                  "Il est temps de r\u00e9pondre \u00e0 100% des appels entrants."
                }
              </span>
            </React.Fragment>
          )}
        </h3>
        <CloudIamNavigationLinkPrimaryCta
          data-plasmic-name={"cloudIamNavigationLinkPrimaryCta"}
          data-plasmic-override={overrides.cloudIamNavigationLinkPrimaryCta}
          className={classNames(
            "__wab_instance",
            sty.cloudIamNavigationLinkPrimaryCta
          )}
          dataTrkciamAction={``}
          dataTrkciamCategory={``}
          dataTrkciamName={``}
          destination={`/contact`}
          openInNewTab={undefined}
        >
          <div
            data-plasmic-name={"text"}
            data-plasmic-override={overrides.text}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text
            )}
          >
            <React.Fragment>
              <React.Fragment>{""}</React.Fragment>
              {
                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__lplAb
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "var(--token-iATmNBw1ODRP)" }}
                    >
                      {"R\u00e9server une d\u00e9mo"}
                    </span>
                  </React.Fragment>
                </h3>
              }
              <React.Fragment>{""}</React.Fragment>
            </React.Fragment>
          </div>
        </CloudIamNavigationLinkPrimaryCta>
      </div>
    </section>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  callToAction: [
    "callToAction",
    "freeBox",
    "cloudIamNavigationLinkPrimaryCta",
    "text"
  ],
  freeBox: ["freeBox", "cloudIamNavigationLinkPrimaryCta", "text"],
  cloudIamNavigationLinkPrimaryCta: [
    "cloudIamNavigationLinkPrimaryCta",
    "text"
  ],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  callToAction: "section";
  freeBox: "div";
  cloudIamNavigationLinkPrimaryCta: typeof CloudIamNavigationLinkPrimaryCta;
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCallToAction__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCallToAction__VariantsArgs;
    args?: PlasmicCallToAction__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicCallToAction__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicCallToAction__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCallToAction__ArgProps,
          internalVariantPropNames: PlasmicCallToAction__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCallToAction__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "callToAction") {
    func.displayName = "PlasmicCallToAction";
  } else {
    func.displayName = `PlasmicCallToAction.${nodeName}`;
  }
  return func;
}

export const PlasmicCallToAction = Object.assign(
  // Top-level PlasmicCallToAction renders the root element
  makeNodeComponent("callToAction"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    cloudIamNavigationLinkPrimaryCta: makeNodeComponent(
      "cloudIamNavigationLinkPrimaryCta"
    ),
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicCallToAction
    internalVariantProps: PlasmicCallToAction__VariantProps,
    internalArgProps: PlasmicCallToAction__ArgProps
  }
);

export default PlasmicCallToAction;
/* prettier-ignore-end */
